### ISSUE TITLE
Propose removing source management from the store (for now)

### ISSUE THREAD

**Issue by local-optimum** [ubuntu/app-center#1068]
![image](https://user-images.githubusercontent.com/55029393/219334548-0a65a65c-25ca-48e6-b095-1ae59387b23d.png)

To avoid too much duplication of information across the OS I propose we simply link the 'configure' button in Settings to Software & Updates to manage PPAs. Whilst down the line I can see this being a potential part of the Store we should do that within the wider context of information surfacing across our various software management apps.

**Comment by Feichtmeier** [comment]
Very good idea

**Comment by Feichtmeier** [comment]
Note: we need the "open" interface thing here too

**Comment by anasereijo** [comment]
closing as this is not an issue anymore. re-open if I am wrong! :)
