### ISSUE TITLE
update text on search results empty stated

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1072]
### how it currently looks like
![VirtualBox_Ubuntu Linux Clone_16_02_2023_11_28_18](https://user-images.githubusercontent.com/36884067/219356020-355dad51-1a76-41ba-95d0-795630edd1a5.png)

### Proposal
<img width="1347" alt="Screenshot 2023-02-16 at 11 43 05" src="https://user-images.githubusercontent.com/36884067/219355943-689e99ad-63bb-4334-a03e-263f6c2deeff.png">

**Comment by Feichtmeier** [comment]
This bird was ofc only a placeholder :)

But this envelope symbol? Are you sure about this? It almost looks like something broke, to me. I would vote for some graphical illustration in some outline and/or origami style

**Comment by madsrh** [comment]
@Feichtmeier the envelope is also just a placeholder 😅

**Comment by anasereijo** [comment]
> This bird was ofc only a placeholder :)
> 
> But this envelope symbol? Are you sure about this? It almost looks like something broke, to me. I would vote for some graphical illustration in some outline and/or origami style

heheh that is just a placeholder!!! so we have to create a nice illustration for it. Btw this issue is just about the TEXT and not the illustration. 
Illustrations are being tracked [here](https://github.com/ubuntu-flutter-community/software/discussions/742)

**Comment by Feichtmeier** [comment]
puhhh ok! I thought that was the icon 😆

**Comment by madsrh** [comment]
I don't know how to get the "asgdha" search string 😔 @Feichtmeier could you point me in the right direction (again)?

**Comment by d-loose** [comment]
Resolved in the current design
