### ISSUE TITLE
update feedback message on category filter empty state

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1073]
### how it looks like
![zerocategories](https://user-images.githubusercontent.com/36884067/219357077-ed7d0d52-68f0-4ff6-826e-52538ed7c1d8.png)

### proposal

<img width="1262" alt="Screenshot 2023-02-16 at 11 48 24" src="https://user-images.githubusercontent.com/36884067/219357047-91ad5178-ae4c-47ce-901c-62aab8a14c6b.png">

**Comment by madsrh** [comment]
If this just moving the text above the image and styling the font a bit, I think maybe I can tackle this. I'll give it a try.

I would love a better (no offense) illustration though 🐣 ❓

**Comment by Feichtmeier** [comment]
this is basically the same as https://github.com/ubuntu-flutter-community/software/issues/1072 from a coding perspective. Can we bundle this issue into one?

**Comment by madsrh** [comment]
> Can we bundle this issue into one?

Yes if that is easier.

I've assigned myself because this is low hanging fruit that I can fix in a couple of days 😜 but feel free to fix it. You've already spend more time reading this than it would take you to fix the issue 😊

**Comment by anasereijo** [comment]
> this is basically the same as #1072 from a coding perspective. Can we bundle this issue into one?

whatever works best for you guys! :))

the messages are different though (the text)

**Comment by Feichtmeier** [comment]
depends

do you want to show a page with always the same "???" icon but with different messages. Or do you want X "not found" pages with X icons and X messages?

**Comment by anasereijo** [comment]
I don't mind having the same icon for the search empty state (or different if anyone has a strong opinion), but I do think we should display different messages, hence I created separate issues.

**Comment by d-loose** [comment]
Resolved in the current design
