### ISSUE TITLE
Disable search by publisher for deb

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#1090]
The information is too unreliable. For snaps we can check the exact username or even id. For debian this is sadly not really possible, at least not with appstream and packagekit. Which results in a misleading UI state after you clicked the publisher name "nothing found" when they click on for example Inkscape

**Comment by anasereijo** [comment]
@Feichtmeier just came across that issue. I see you say it's not really possible, which unfortunately will make the experience a bit more confusing as we allow that on snaps. I will add this to a list of things to check.

https://user-images.githubusercontent.com/36884067/229467378-b780cde2-8229-42d1-82e2-f793476341e8.mov

**Comment by anasereijo** [comment]
Wondering if there is anything we can do to find a solution before we disable it. 🤔

@jpnurmi any thoughts?

**Comment by Feichtmeier** [comment]
The mapping between publishers and his apps is crystal clear and 100% correct for snaps
For debian and appstream there is metdata for project_group and developer_name but the last time I searched there it was quite unreliable eventually not even possible, but I need to re-check this, can not confirm this 100%

**Comment by d-loose** [comment]
App-center doesn't support search by publisher (yet), so this issue isn't relevant anymore
