### ISSUE TITLE
ExplorePage: show top rated apps

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#1096]
@jpnurmi since you worked on the ratings, could you do this?

Mock-Up:

![](https://user-images.githubusercontent.com/36884067/218127988-2c9f9788-5ac5-4264-960c-4994c8cd9573.png)
![](https://user-images.githubusercontent.com/36884067/218127929-273e311f-c2f0-42c0-bb4e-0776b81adcfc.png)

**Comment by madsrh** [comment]
⭐ ⭐ ⭐  ⭐ ⭐ 

I just remembered this: 
https://wiki.ubuntu.com/SoftwareCenter#A.2BIBw-Top_Rated.2BIB0_overall

**Comment by anasereijo** [comment]
@jpnurmi I guess you'll have to be in touch with the store team as they will be working on the APIs for the explore page

**Comment by Feichtmeier** [comment]
Hey @anasereijo :wave: 

Currently working on this. What I don't understood what the consesus between you, oliver and sqrt(ana²) (the other ana :D) about the shortcuts?

For example games: do you want to keep the shortcuts for games but also show them on the explorepage? No opinion, just want to be sure

**Comment by anasereijo** [comment]
> For example games: do you want to keep the shortcuts for games but also show them on the explorepage? No opinion, just want to be sure

Hey @Feichtmeier! 👋 

The banners/collections on the explore page are supposed to be replaced from time to time, so there is not really an issue 'repeating' games. The content you see on the mock-up are placeholders, hopefully we will have someone curating this for us. 

One thing we need to think about is a 'quick' and 'easy' way to update those banners/collections. We plan to use this also on snapcraft.io, so maybe we should align this with @Lukewh. Can this be pulled from a spreadsheet? Or any other ideas?

**Comment by Feichtmeier** [comment]
Yes this sounds like the best idea. As always we are doing better when we only consume what the servers are giving us

Maybe at a new category type

'frontPageSection1'
'frontPageSection2'
'frontPageSection3'
etc
Or a list of lists of snaps

**Comment by Lukewh** [comment]
We will add new "hidden" categories in the store API, we need to discuss with the store team, but it isn't a big task once we've decided what we want / how they should be named 🙂

**Comment by Feichtmeier** [comment]
> We will add new "hidden" categories in the store API, we need to discuss with the store team, but it isn't a big task once we've decided what we want / how they should be named 🙂

Cool then I spent my time on code clean ups until then 😅

**Comment by anasereijo** [comment]
closing as we are currently working on the APIs for this.
