### ISSUE TITLE
Showing empty review if no reviews exist

### ISSUE THREAD

**Issue by madsrh** [ubuntu/app-center#1136]
When an app has no reviews this empty review is shown 👇 
I think we should provide a simple "There are no reviews yet" text and in case that the app is installed, but still has no reviews ofc. show the rating stars.

![image](https://user-images.githubusercontent.com/3986894/222085737-59e97543-ef51-48b4-b8e6-28862cffff2b.png)

### Not installed, no reviews:
![image](https://user-images.githubusercontent.com/3986894/222086109-f9a82e4d-1410-43a4-a395-4e3ded8a0651.png)

### Installed, but no reivews:
![image](https://user-images.githubusercontent.com/3986894/222086178-5a7a6339-1565-42d2-99fd-3804a8aa18f5.png)

**Comment by anasereijo** [comment]
Sorry if nitpicking, but what do you think about replacing the exclamation mark with the full stop? Also, what do you think about saying review instead or rate?

There are no reviews yet. Be the first to review Spotify.

**Comment by Feichtmeier** [comment]
Also fix this in the 🐕‍🦺🐾 service

**Comment by anasereijo** [comment]
Closing, as we currently don't display the Review and Ratings sections.
