### ISSUE TITLE
Spotify reviews and ratings weren't displaying

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1171]
I opened the Spotify page, and the reviews weren't showing up - See screenshots. 
I wanted a bit, and still nothing. I then went back and opened again, and it is showing properly now. However, maybe we should check if there is some issue with the backend? 

<img width="1680" alt="Screenshot 2023-03-22 at 11 51 18" src="https://user-images.githubusercontent.com/36884067/226897963-b9c5fb81-19c4-4cc2-a32c-deafe7044af6.png">
<img width="1680" alt="Screenshot 2023-03-22 at 11 51 29" src="https://user-images.githubusercontent.com/36884067/226898020-f80f4b0a-689a-48ee-b138-24673ac240ea.png">

**Comment by anasereijo** [comment]
@Feichtmeier I went back to search and opened it again, and it is showing up now. But maybe worth checking what happened?

**Comment by Feichtmeier** [comment]
absolutely
maybe it is fragile when the network drops off and we need to resend the request

**Comment by d-loose** [comment]
Outdated - we'll have a different rating system in app-center.
