### ISSUE TITLE
Move "Sort by" label out of dropdown

### ISSUE THREAD

**Issue by madsrh** [ubuntu/app-center#1190]
Collections/Manage page: This label shouldn't be inside the dropdown.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3986894/227660714-4f703365-d149-4890-b126-18825522c20e.png">

This version would fit with the Material design:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/3986894/227660621-3e42ac60-f29c-4b12-837a-f7cc0428b0ff.png">

Or simply add a traditionel label:
![image](https://user-images.githubusercontent.com/3986894/227660548-6a0e9be8-e2ab-4e87-8ec2-7880fab32cf1.png)

**Comment by Feichtmeier** [comment]
Yes, this sortby is redundant. I would prefer to remove it

**Comment by madsrh** [comment]
> Yes, this sortby is redundant. I would prefer to remove it

Yeah, it isn't working here (but maybe I've broken it 🙈). I think it would be useful for some - if you are low on diskspace - to sort by size 🤷‍♂️

**Comment by Feichtmeier** [comment]
hmm? no i mean the "sort by" label is redundant not the dropdown :)

**Comment by anasereijo** [comment]
If we keep it, I'd do what @madsrh is proposing, moving it out of the dropdown. 

I also understand @Feichtmeier's point of view, but I think this should be looked at as an overall thing, looking at all filters and dropdowns and check whether we keep labels or not, also aligning things between pages to keep consistency. That said, I'd recommend keeping it for now, and maybe we can create a separate issue to look at filter/labels across the app.

**Comment by madsrh** [comment]
Okay, what do you think about removing it for now? That way it's consistent with the "snap package" drop-down as it looks now and we can, as you suggest, revisit this later.
