### ISSUE TITLE
Manage: remove system deb updates

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#1199]
"apps" being updated in the debian tab of the manage page is a nice feature

However, the power to update your system is limited

1) repairing/partly upgrade does not work yet and you still need system updater
![grafik](https://user-images.githubusercontent.com/15329494/228807004-076ab0e5-57e7-4e2e-b4d7-8c8f48f4a572.png)
(I think this is not supported in packagekit)
2) the full release upgrade does not work yet (I think this might be working with packagekit but we did not follow this feature here)

So to get the app ready for 23.10, let's filter out all deb updates that are not "apps" the user installed

(The same should IMO also happen for the normal installed packages, I don't want to be responsible for people removing lib xyz because we allow this packagekit filter to be selected, even though some users complained they want it here, I disagree and think this is too risky for an "app store")

**Comment by d-loose** [comment]
Did we find a way to launch `update-manager` and `software-properties-gtk` from the confined snap environment? If so, can someone remind me how? :)

**Comment by Feichtmeier** [comment]
I tried some weeks ago but the only thing that worked was to launch it nested inside a shell which is ofc no solution. Chatted a bit with Ken about it but we didn't find a reason at this day
