### ISSUE TITLE
Match 'Links' section with snapcraft.io

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1204]
Seems that we always display a link called 'Website' that takes the user to the snap page on snapcraft.io. This section should display the same links we have on snapcraft.io.

I think that we have done this before, and found a screenshot [here](https://github.com/ubuntu-flutter-community/software/issues/796#issuecomment-1398229026). Can't remember what happened after that anymore 😅

<img width="784" alt="Screenshot 2023-03-31 at 14 46 44" src="https://user-images.githubusercontent.com/36884067/229137656-9b9db185-4534-467b-854b-a153915c021a.png">

<img width="515" alt="Screenshot 2023-03-31 at 14 46 59" src="https://user-images.githubusercontent.com/36884067/229137697-151a7b8c-a097-4955-b513-bacdf5aa0f9b.png">

**Comment by d-loose** [comment]
Resolved in current design
