### ISSUE TITLE
Make Snapcrafters show as a verified account

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1209]
On [snapcraft.io](https://snapcraft.io/publisher/snapcrafters), Snapcrafters is a Verified account.
<img width="583" alt="Screenshot 2023-04-03 at 11 00 26" src="https://user-images.githubusercontent.com/36884067/229478400-00652343-7dd7-4444-9d69-8006a771e4df.png">

We don't display the verified account icon on the Software store.
<img width="1361" alt="Screenshot 2023-04-03 at 11 00 17" src="https://user-images.githubusercontent.com/36884067/229478447-02507286-e976-4c84-9d37-14545e2c2d66.png">
<img width="632" alt="Screenshot 2023-04-03 at 11 00 03" src="https://user-images.githubusercontent.com/36884067/229478461-d194288d-bca8-4e43-9dbe-cf6219fac1f0.png">

**Comment by anasereijo** [comment]
Just noticed that on snapcraft.io, the icon is displayed just on the [snapcrafters](https://snapcraft.io/publisher/snapcrafters) landing page, but not on the snap pages or the search results.

<img width="687" alt="Screenshot 2023-04-03 at 11 04 36" src="https://user-images.githubusercontent.com/36884067/229478861-5af0bbf1-2de8-4486-8cef-734dc463d79c.png">
<img width="1113" alt="Screenshot 2023-04-03 at 11 04 30" src="https://user-images.githubusercontent.com/36884067/229478877-6bb39055-d9c9-47d5-b20d-3194d0782dfe.png">

created an [issue](https://github.com/canonical/snapcraft.io/issues/4236) for that

**Comment by d-loose** [comment]
Fixed upstream :tada:
