### ISSUE TITLE
Code block isn't 'rendering' well on app description

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1211]
Code block isn't 'rendering' on app description:

<img width="1147" alt="Screenshot 2023-04-03 at 12 35 46" src="https://user-images.githubusercontent.com/36884067/229525204-84352bd0-2dc6-4f2a-ba64-3d0186d2b774.png">

how it looks on [snapcraft.io](https://snapcraft.io/bookmark-cd):
<img width="803" alt="Screenshot 2023-04-03 at 14 30 41" src="https://user-images.githubusercontent.com/36884067/229525341-1c7ce56e-0be8-4b07-b5c0-409a44ab1af3.png">

not sure if helpful, but on the website we use the [code block](https://vanillaframework.io/docs/base/code#block) from Vanilla.

**Comment by BLKKKBVSIK** [comment]
We don't have the identifiers to treat it the code block. Reported to later.

**Comment by anasereijo** [comment]
@BLKKKBVSIK sorry, not sure what you mean. On Snapcraft we display code block (See screenshot). Is this something missing in our libraries?

<img width="920" alt="Screenshot 2024-01-02 at 14 17 31" src="https://github.com/ubuntu/app-center/assets/36884067/e3bcfda8-a0b9-41d9-9f95-f624ccafba40">

**Comment by d-loose** [comment]
> From the data that we receive from Snapcraft, we can't identify what is or isn't a code block.

IIRC some snapcraft metadata uses indented code blocks instead of backticks. Maybe the markdown dart package has a problem with that?

**Comment by d-loose** [comment]
```
$ curl -s --unix-socket /var/run/snapd.socket "http://localhost/v2/find?name=bookmark-cd" | jq -r '.result[0].description'
`bcd` is a way to cd to directories that have been bookmarked.

Snapcraft does not allow write access to the shell init scripts which are required to set up `bcd` so the following commmand should be set up manually in your `~/.bashrc` if you are using bash or `~/.zshrc` if you are using zsh as your shell:

   # bookmark-cd init block
   eval "$(bookmark-cd init)"   

```
Looks like the code block is indented by only three spaces. The markdown package parses that as
```
<p><code>bcd</code> is a way to cd to directories that have been bookmarked.</p>
<p>Snapcraft does not allow write access to the shell init scripts which are required to set up <code>bcd</code> so the following commmand should be set up manually in your <code>~/.bashrc</code> if you are using bash or <code>~/.zshrc</code> if you are using zsh as your shell:</p>
<h1>bookmark-cd init block</h1>
<p>eval &quot;$(bookmark-cd init)&quot;</p>
```
With four spaces it gives
```
<p><code>bcd</code> is a way to cd to directories that have been bookmarked.</p>
<p>Snapcraft does not allow write access to the shell init scripts which are required to set up <code>bcd</code> so the following commmand should be set up manually in your <code>~/.bashrc</code> if you are using bash or <code>~/.zshrc</code> if you are using zsh as your shell:</p>
<pre><code># bookmark-cd init block
eval &quot;$(bookmark-cd init)&quot;   
</code></pre>
```
as expected.

No idea why it works on the website, but in principle this should be fixed by the maintainer of the snap.

**Comment by BLKKKBVSIK** [comment]
If that's a maintainer issue and not an app-center issue, I guess we can close this one.
