### ISSUE TITLE
search: filter by category can show unexpected results

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1214]
Can we investigate how/why we get some results not related to the selected category? 

For instance, I searched for Firefox and filtered by 'Games' – none of the results are games.
<img width="1748" alt="Screenshot 2023-04-04 at 15 28 17" src="https://user-images.githubusercontent.com/36884067/229826301-8949bb5e-5a2c-4347-b26f-7d2b99c73c90.png">

Other example:
<img width="1748" alt="Screenshot 2023-04-04 at 15 34 43" src="https://user-images.githubusercontent.com/36884067/229826774-dff37f27-571c-425e-be1e-3040873af8f0.png">

and another one:
<img width="1748" alt="Screenshot 2023-04-04 at 15 36 20" src="https://user-images.githubusercontent.com/36884067/229827167-e5c14f0f-e2a8-45cb-b97f-c29206a25031.png">

**Comment by Feichtmeier** [comment]
All debian packages are not filtered by catergories.

Issues related are:
- #560 

If we won't be able to filter debian packages by categories, should we hide them if a category is specified @anasereijo ?
(just thinking, I don't know if this will be possible in the end)

**Comment by anasereijo** [comment]
good points @Feichtmeier 

is it also related to this? https://bugs.launchpad.net/snapstore-server/+bug/1998482 If so, I can try pushing it internally and see if we get some help

**Comment by anasereijo** [comment]
So, if I ignore Debs we still see Firefox snap on the Game category and the same for Solitaire on Security. 
Wondering if it's okay or not... at the same time it's the exact query the user searched for, but it doesn't really belong to that category 🤔 maybe nitpicking but worth thinking about it

**Comment by Feichtmeier** [comment]
> So, if I ignore Debs we still see Firefox snap on the Game category and the same for Solitaire on Security.
Wondering if it's okay or not... at the same time it's the exact query the user searched for, but it doesn't really belong to that category thinking maybe nitpicking but worth thinking about it

Yes you are right. I have forgotten about our most recent addition to search which also returns the 1:1 match. We added this because we wanted the steam snap to show up even though it is unlisted
So this is indeed a bug!

**Comment by Feichtmeier** [comment]
I could quick fix this by asking for the selected category filter, however to make this a good fix we need https://github.com/ubuntu-flutter-community/software/issues/941 so I could check for selected category ==  category of exact match finding

**Comment by anasereijo** [comment]
Cool! Maybe worth waiting for the good fix, then.

**Comment by Feichtmeier** [comment]
So recapping:

1) Debian packages showing corresponding to the filter needs a mapping of appstream categories (but I am not sure they exist) to snap categories
2) the other issue is a bug which is fixable

**Comment by anasereijo** [comment]
Number 1 would be super nice to have. Let me know if there's anything I can help with in terms of asking for support or anything else

**Comment by Feichtmeier** [comment]
Just re-checked and it is possible to check this. I'll add the mapping between snap and appstream categories first, then we can check for the category selected when adding debian search result to the search results and decide whether to add them or not

**Comment by d-loose** [comment]
Not an issue in app center, as we're not using categories for debian packages yet.
