### ISSUE TITLE
Deb packages cannot be clicked, often second letter isn't clicked

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1237]
[Screencast from 2023-05-24 02-19-15.webm](https://github.com/ubuntu-flutter-community/software/assets/72045785/09a72d81-a55c-43e0-832b-b1da318979f1)

Additional details:

Ubuntu 23.04
nvidia-525 proprietary drivers in Xorg
Intel i7-11800H

**Comment by Feichtmeier** [comment]
Yes this is due to the fact that the code to search for debs needs a bit more time to prepare than the one for snaps

See https://github.com/ubuntu-flutter-community/software/discussions/1236

**Comment by Feichtmeier** [comment]
But nevertheless it's an issue we need to fix
