### ISSUE TITLE
Cached network image does notplay well with multiple users

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#1272]
Just noticed in musicpod and then confirmed in software that when you run the app with one account it works fine to load the image then you log into another account in ubuntu and the images are not loading.
I wonder if this is fixable with a specific setting of cachednetworimage otherwise I fear we might need to remove it

**Comment by Feichtmeier** [comment]
https://github.com/renefloor/flutter_cache_manager

**Comment by d-loose** [comment]
This has been resolved here https://github.com/ubuntu/app-center/commit/9dc23484ed591412b744de7501407504ead5affa, by using `XDG_CACHE_HOME` instead of `/tmp` as a cache directory.

**Comment by Feichtmeier** [comment]
> This has been resolved here https://github.com/ubuntu/app-center/commit/9dc23484ed591412b744de7501407504ead5affa, by using `XDG_CACHE_HOME` instead of `/tmp` as a cache directory.

Thanks, will try the same for MusicPod
