### ISSUE TITLE
Do not show Debian packages without AppStream metadata in installed packages list

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/app-center#1273]
There is no real benefit for most users in showing every package installed on the system. It is confusing and potentially dangerous since users are able to uninstall any of these packages by mistake.

Please, consider implementing what the current gnome-software based Ubuntu Software app does: Show just packages that have AppStream metadata - either included appdata/metainfo file or packages without included appdata/metainfo file, but containing a desktop file and thus having AppStream metadata automatically generated by [appstream-generator](https://appstream.ubuntu.com).

This will make the Debian installed packages list much more clearer and user friendly + will significantly help with #1106.

**Comment by d-loose** [comment]
This doesn't apply to the new app-center yet, since we haven't implemented a manage page for debian packages yet.
It's a good suggestion and we intend to build it with a focus on applications rather than individual packages.
