### ISSUE TITLE
Search does not work when locale is nl_NL

### ISSUE THREAD

**Issue by nicktelindert** [ubuntu/app-center#1275]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AppLocalizations.delegate failed to load unsupported locale "nl_NL". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
#0      lookupAppLocalizations (package:flutter_gen/gen_l10n/app_localizations.dart:1403)
#1      AppstreamService._greylist (package:software/services/appstream/appstream_service.dart:140)
#2      AppstreamService._buildSearchTokens.<anonymous closure> (package:software/services/appstream/appstream_service.dart:182)
#3      ListBase._filter (dart:collection/list.dart:293)
#4      ListBase.removeWhere (dart:collection/list.dart:281)
#5      AppstreamService._buildSearchTokens (package:software/services/appstream/appstream_service.dart:182)
#6      AppstreamService.search (package:software/services/appstream/appstream_service.dart:204)
#7      ExploreModel._findAppstreamComponents (package:software/app/explore/explore_model.dart:151)
#8      ExploreModel.search (package:software/app/explore/explore_model.dart:253)
<asynchronous suspension>

**Comment by d-loose** [comment]
Sorry, overlooked this issue when opening a new one - continuing in #1397
