### ISSUE TITLE
Geary isn't showing up in the app-store

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1305]
When searched for `geary` it's not showing up in the searches of the app-store. 

![image](https://github.com/ubuntu/app-store/assets/72045785/7749d2f1-960e-4238-b0c2-98aa434cb5d4)

But, it's indeed in the Ubuntu repo.

https://packages.ubuntu.com/lunar/geary

The app-store version is 0.3.0-alpha and I'm using Ubuntu 23.04

**Comment by Feichtmeier** [comment]
![grafik](https://github.com/ubuntu/app-store/assets/15329494/2ba80f5c-6db7-4d06-ad7b-338dd1bef2b8)
nope, its there :)

**Comment by soumyaDghosh** [comment]
![image](https://github.com/ubuntu/app-store/assets/72045785/2c3a08b8-868d-4c1d-8fc5-a1f67b89fe9f)


This screenshot is what I took just now! And look at this once

**Comment by Feichtmeier** [comment]
CC @d-loose

**Comment by soumyaDghosh** [comment]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Concurrent modification during iteration: _Map len:12.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:710)
#1      Future.forEach.<anonymous closure> (dart:async/future.dart:649)
#2      Future.doWhile.<anonymous closure> (dart:async/future.dart:707)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#4      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1633)
<asynchronous suspension>
#5      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1633)
<asynchronous suspension>
```

Error code when I search `geary`

**Comment by d-loose** [comment]
Confirmed this is still an issue in the app-center. Seems like the problem is that the snowball stemmer used in the appstream service's search algorithm turns "geary" into "geari".

**Comment by d-loose** [comment]
While looking into this, I found a related issue: #1397.

The fact that "Geary" appears in @Feichtmeier's results, but not in @soumyaDghosh's is because the German stemming algorithm keeps "Geary" intact, while the English one turns it into "Geari".

I think we should probably just keep the original search query along with the ones generated from the stemming algorithm.
