### ISSUE TITLE
Define and design error handling UX

### ISSUE THREAD

**Issue by d-loose** [ubuntu/app-center#1362]
We need to define how/if errors are presented to the user.
The most common case we need to handle is the failure of a user-initiated action (i.e. error during installation/refresh/removal - can happen e.g. because there's already another action in progress, or for various other reasons like network failure).

Maybe a simple modal dialog (like here: https://github.com/canonical/firmware-updater/pull/101) is enough for now?

**Comment by anasereijo** [comment]
closing as I believe we covered all this in the recent work. @d-loose pls let me know if that's not the case.
