### ISSUE TITLE
Sidebar navigation not highlighted when clicking section on explore page

### ISSUE THREAD

**Issue by tim-hm** [ubuntu/app-center#1379]
## issue

1. Activate explore page
2. Scroll down to a banner (ie "Featured Snaps" or "Must have snaps for developers")
3. Click "Discover more"
4. The correct page is activated but it has a back button and the left side navigation isn't selected.

![image](https://github.com/ubuntu/app-center/assets/1335525/f8f6009f-3252-42a8-828e-33457a25a1fc)

## expected behaviour

When activating a 'top level' section, I would expect the left nav bar to reflect the active page.

**Comment by d-loose** [comment]
That was a deliberate design choice. Do we need to rethink this? @anasereijo?

**Comment by anasereijo** [comment]
@d-loose as discussed on standup, if a category is selected from the Explore page, and it's also present on the side-nav, the side-nav item should become highlighted.
