### ISSUE TITLE
Debian icons not loading

### ISSUE THREAD

**Issue by tim-hm** [ubuntu/app-center#1382]
My console is getting spammed with 404s when trying to resolve a Debian icon. I assume you're aware, but if not this is what I'm seeing every time it tries to resolve the icon:

```
======== Exception caught by image resource service ================================================
The following HttpExceptionWithStatus was thrown resolving an image codec:
HttpException: Invalid statusCode: 404, uri = https://appstream.ubuntu.com/media/mantic/l/lx/lxqt-xfwmtweaks.desktop/2D4A72EAA2C974FBBED9E03ECD7CC6C0/icons/128x128/lxqt-branding-debian_wmtweaks.png

When the exception was thrown, this was the stack: 
Image provider: CachedNetworkImageProvider("https://appstream.ubuntu.com/media/mantic/l/lx/lxqt-xfwmtweaks.desktop/2D4A72EAA2C974FBBED9E03ECD7CC6C0/icons/128x128/lxqt-branding-debian_wmtweaks.png", scale: 1.0) 
 Image key: CachedNetworkImageProvider("https://appstream.ubuntu.com/media/mantic/l/lx/lxqt-xfwmtweaks.desktop/2D4A72EAA2C974FBBED9E03ECD7CC6C0/icons/128x128/lxqt-branding-debian_wmtweaks.png", scale: 1.0): CachedNetworkImageProvider("https://appstream.ubuntu.com/media/mantic/l/lx/lxqt-xfwmtweaks.desktop/2D4A72EAA2C974FBBED9E03ECD7CC6C0/icons/128x128/lxqt-branding-debian_wmtweaks.png", scale: 1.0)
====================================================================================
```

**Comment by d-loose** [comment]
I noticed that some icon urls lead to nowhere, but the UI handles this correctly and shows a fallback icon in this case (e.g. [libreoffice-writer](https://appstream.ubuntu.com/media/lunar-updates/l/li/libreoffice-writer.desktop/70778e112672d6caea2b3abbf6173b6c/icons/128x128/libreoffice-writer_libreoffice-writer.png).
The fact that the exception is shown in the debug console, even though it's being properly handled by the `errorBuilder` seems like a [bug in flutter itself](https://github.com/flutter/flutter/issues/129967). Those errors shouldn't make it to stderr when running the application in release mode, though - can you confirm?

**Comment by tim-hm** [comment]
When its running as a snap I don't see these traces

**Comment by d-loose** [comment]
e.g. the icon for [blender](https://github.com/ubuntu/app-center/issues/1382) should load without issues.

**Comment by d-loose** [comment]
As far as I can tell appstream metadata is available in mantic now - can you confirm this is fixed @tim-hm?
