### ISSUE TITLE
Log errors and other useful information

### ISSUE THREAD

**Issue by d-loose** [ubuntu/app-center#1394]
We need to log errors and other relevant information so that users can provide us with more detailed bug reports in the future.

**Comment by anasereijo** [comment]
@d-loose is this still relevant?

**Comment by d-loose** [comment]
Logging errors is of course always relevant! But I used this issue specifically for https://github.com/ubuntu/app-center/pull/1396 and https://github.com/ubuntu/app-center/pull/1418, so I'll close it now.
