### ISSUE TITLE
Cannot update a snap from within the snap page

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1399]
[Screencast from 2023-09-21 21-07-41.webm](https://github.com/ubuntu/app-center/assets/72045785/08cb3e06-327e-43c7-9943-b2aa47f19aa9)

**Comment by d-loose** [comment]
Your screencast is showing the archived community store - please stick to bug reports for the app center (which is now included in the daily builds of ubuntu mantic and can be found in the latest/stable/ubuntu-23.10 snap channel).
