### ISSUE TITLE
Search often gets stuck and opening and closing the app also doesn't help

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1400]
[Screencast from 2023-09-21 22-37-03.webm](https://github.com/ubuntu/app-center/assets/72045785/34918416-2d42-4a46-bdbc-a360b270f4f4)

[Screencast from 2023-09-21 22-39-25.webm](https://github.com/ubuntu/app-center/assets/72045785/b79c3c65-88ec-4245-97b2-b17f49f5d54e)

**Comment by d-loose** [comment]
Thanks!
I can confirm this bug - seems like one can somehow end up selecting the "Snap packages" and "Deb packages" title in the menu.. I'll investigate
