### ISSUE TITLE
Search for deb packages fails due to unsupported locale

### ISSUE THREAD

**Issue by DiogoConstantino** [ubuntu/app-center#1401]
I'm running 1.0.0-alpha (on Ubuntu 23.10 beta).

When I search for a package and select the option "Debian packages", I get the following message:

`AppLocalizations.delegate failed to load unsupported locale "pt". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-I10 configuration that was used.`

![imagem](https://github.com/ubuntu/app-center/assets/9408012/b1074508-7e9c-49f1-be24-71a5ad7aeb5d)

The build used was whatever is included on the Ubuntu 23.10. I was just testing the beta. The system is configured for pt_PT since installation, and I completed the language installation (libreoffice localization doesn't install by default) using the language definitions.

**Comment by d-loose** [comment]
Thanks for the detailed bug report! It's a known issue, see #1397. Will fix it soon :)

**Comment by DiogoConstantino** [comment]
Thank you, I looked for a bug before reporting, but obviously, I missed that, thank you for your time!

**Comment by d-loose** [comment]
Thanks, no worries, there are still a ton of outdated issues that may or may not be still relevant and I haven't had the time to go through all of them yet.
#1402 should fix this!
