### ISSUE TITLE
Can't update one single snap in the store

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1410]
![Screenshot from 2023-09-26 19-11-26](https://github.com/ubuntu/app-center/assets/72045785/92e280ae-3ae5-4b24-90f1-adbb1d8d2b3e)

I can't find any option to update only one snap in the list. I don't want to update all of them just now, simply due to limited amount of internet.

**Comment by d-loose** [comment]
Thanks - we didn't land that feature yet, but definitely plan to include it!

**Comment by codinesh** [comment]
#1538 will fix this.
