### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1419]
Hi,

Today I tried to install Flameshot snap. I clicked on "install" then... nothing, the wheel turns two seconds and that's all.

In terminal:
```
$ snap install flameshot 
erreur : cannot perform the following tasks:
- Assurez-vous que les prérequis pour "flameshot" sont disponibles (cannot install prerequisite "kde-frameworks-5-91-qt-5-15-3-core20": no snap revision available as specified)
```

So is it possible, like Synaptic does, to be informed about what went wrong (popup)?

**Comment by d-loose** [comment]
Yes! #1396 and #1418 are now merged into dev and we'll merge recent bug fixes and improvements into main soon - making them available in the upcoming version

**Comment by fthx** [comment]
Great!
(PS: I've got a message for you here: https://discourse.ubuntu.com/t/ubuntu-channel-snaps/38593/5)
