### ISSUE TITLE
Add option to flag or report snaps

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1423]
There is a recent [post](https://forum.snapcraft.io/t/temporary-suspension-of-automatic-snap-registration-following-security-incident/37077) on snapcraft about apps being removed from the store, for being phishing apps. Please add a button so the users can be directed straight to snapcraft forum or open a text box for them to report the snap app.

**Comment by anasereijo** [comment]
Thanks for your feedback @alculete !
I am closing as this is this issue is being tracked [here](https://github.com/ubuntu/app-center/issues/1490)
