### ISSUE TITLE
The padding in the central window is too aggressive

### ISSUE THREAD

**Issue by local-optimum** [ubuntu/app-center#1428]
The padding in the store window is too generous and switches to a single column view too early when scaling the windows, creating a lot of empty space and cramped content. This is especially noticeable when looking at screenshots in apps which are too small in this view. Can we tune the padding for a nicer experience.

![image](https://github.com/ubuntu/app-center/assets/55029393/06161fec-443d-4d97-98e5-966cf165c4c3)
[Screencast from 02-10-23 09:13:45.webm](https://github.com/ubuntu/app-center/assets/55029393/d8b2287b-f358-4bdf-bbe5-b60d7d8df7e1)

**Comment by FussuChalice** [comment]
Yup! Please mark with a marker where you do not like pedings. Thank you in advance.

**Comment by Feichtmeier** [comment]
+1
would be nice to get back to the old padding (20px) and the adaptive grid IMO

**Comment by BLKKKBVSIK** [comment]
@anasereijo Still an issue nowaday ?

**Comment by anasereijo** [comment]
@BLKKKBVSIK we should look into this at some point
