### ISSUE TITLE
Check for Updates button suddenly gone while the operation was done and I was scrolling the apps

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1429]
![image](https://github.com/ubuntu/app-center/assets/72045785/73885583-54ef-4d55-8ba0-3d5e3e8be3a9)

**Comment by FussuChalice** [comment]
Can you please post a video of how this happens?

**Comment by soumyaDghosh** [comment]
Not able to reproduce this. Closing this then. Will reopen, when I'll find this again.

**Comment by alculete** [comment]
This happens to me sometimes, for no apparent reason.

**Comment by d-loose** [comment]
Seems like the error state of the `UpdatesModel` isn't properly handled in the UI (the button will indeed appear [empty](https://github.com/ubuntu/app-center/blob/9c4f9ff4f86bd3b083abc1ac4ed2e688d69cd872/lib/src/manage/manage_page.dart#L234) in that case). Could you provide any relevant log files located in `$HOME/snap/snap-store/current/.local/share/snap-store/`?

**Comment by alculete** [comment]
only a broken link is created on this patlinkh

**Comment by d-loose** [comment]
> only a broken link is created on this path

The log files are named `snap-store.log.$PID` and the symbolic link always points to the newest one. If nothing has been logged it just points nowhere.. :D

I'll keep this issue open anyways, since the error state is clearly not handled properly for this button.

**Comment by soumyaDghosh** [comment]
Hii, I was making store refresh of a snap that I have installed locally. While doing so, I opened the manage section and found this.

![image](https://github.com/ubuntu/app-center/assets/72045785/e4bce26d-31ed-493d-b055-aa1f9222fd1b)
