### ISSUE TITLE
App-Center is missing after upgrade from 23.04 to 23.10

### ISSUE THREAD

**Issue by leillo1975** [ubuntu/app-center#1435]
Hello

Some days ago I upgrade my Ubuntu 23.04 OS to 23.10 using "update-manager -d". Everything seems to be ok, I don't see the new app-center anywhere. 
Is this normal? Is it possible to install it manually with apt or snap?

**Comment by d-loose** [comment]
Thanks - this issue is being tracked [here](https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/2036765).

You can update manually using
```
snap refresh --channel=latest/stable/ubuntu-23.10 snap-store
```

**Comment by neidiom** [comment]
When I run

````
snap refresh --channel=latest/stable/ubuntu-23.10 snap-store
````

I get

````
error: snap "snap-store" is not installed
````

**Comment by neidiom** [comment]
Solved by

````
snap install snap-store
snap switch --channel=latest/stable/ubuntu-23.10 snap-store

````
