### ISSUE TITLE
Widgets on the snap page move around during initialization

### ISSUE THREAD

**Issue by d-loose** [ubuntu/app-center#1447]
When the ratings backend responds, the voting data is dynamically added to the snap page. However, the transition is far from smooth (added an artificial delay to emphasize the issue):

[Screencast from 2023-10-06 17-44-12.webm](https://github.com/ubuntu/app-center/assets/113362648/8c8e50f2-9f07-4848-8421-46aa4698a1d2)

We could either display a placeholder with a loading and error state, or move the ratings information to a different spot on the page, where it doesn't disrupt other elements.

**Comment by Feichtmeier** [comment]
I would vote for using the shimmer approach from the past incarnation of app-center
i.e. having a loading app page (detail page?)
