### ISSUE TITLE
Clicking on Share Button Shows no Visual Feedback

### ISSUE THREAD

**Issue by raghavdhingra24** [ubuntu/app-center#1462]
Hi there,
Clicking on the share button present on the app information shows no visual confirmation of what has been done even though the link is copied to the clipboard.

Video for the same:
[Screencast from 2023-10-15 11-22-32.webm](https://github.com/ubuntu/app-center/assets/106472154/0f50ef21-ee3c-4cf7-99bf-ddd1e85b8530)
Regards

**Comment by santiagofn** [comment]
Same here.

- App Center v1.0.0-alpha
- Ubuntu 23.10
