### ISSUE TITLE
Feature: Add deb and snap packages to the same page

### ISSUE THREAD

**Issue by SkylarLK** [ubuntu/app-center#1466]
I recall the previous Ubuntu app center having a mix of both deb and snap packages that were not segregated from each other. I believe this is also the case (at least with Flatpak) in Gnome Software and KDE Discover. Please bring that back. It is impractical to always find the package name and then use sudo apt install for non-snap packages such as Emacs.
Another thing: Show programs that have been installed via deb package as having been already installed. Even though I have the deb package of LibreOffice it shows in the App Center as prompting to install the program as a Snap even though I already have the non-snap version preinstalled.
One last thing: De-emphasize promoting apps in the Explore category that have already been installed on the user's system. If I already have an app installed I don't need to see it up top.

**Comment by juanmmorel** [comment]
I think it is better and more intuitive for the user

**Comment by SkylarLK** [comment]
> I think it is better and more intuitive for the user

This is vague. What do you think is more intuitive?

**Comment by d-loose** [comment]
Since we ran into various technical and UX-related issues trying to present snaps and debs as two options for the same application, we chose to keep them separate. For further details check https://discourse.ubuntu.com/t/pulse-13-ubuntu-desktop-engineering-update/36611.
