### ISSUE TITLE
App Center doesn't follow button layout and custom cursors.

### ISSUE THREAD

**Issue by Octopus1348** [ubuntu/app-center#1469]
App Center, along with the new firmware updater, doesn't follow the button layout set with `gsettings set org.gnome.desktop.wm.preferences button-layout`, and custom cursors set with GNOME Tweaks, while every other snap does.
I ran this command to make snaps follow my GTK theme:
`for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i orchis-themes:gtk-3-themes; done`

`snap connections | grep gtk-common-themes:gtk-3-themes` returns this:
```
content[gtk-3-themes]    dialect:gtk-3-themes                             gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    dolphin-emulator:gtk-3-themes                    gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    firefox:gtk-3-themes                             gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    firmware-updater:gtk-3-themes                    gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    gnome-boxes:gtk-3-themes                         gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    gnome-calendar:gtk-3-themes                      gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    pinta:gtk-3-themes                               gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    snap-store:gtk-3-themes                          gtk-common-themes:gtk-3-themes  -
content[gtk-3-themes]    snapd-desktop-integration:gtk-3-themes           gtk-common-themes:gtk-3-themes  -
```
The output also includes Firmware Updater, and App Center.

**Comment by d-loose** [comment]
This is a general limitation of the way Flutter applications are currently being developed for the Ubuntu desktop - we use a [Flutter implementation](https://github.com/ubuntu/yaru.dart) of the [yaru theme](https://github.com/ubuntu/yaru). While the theme of native GTK applications can be modified in the way you describe this isn't currently possible for our Flutter applications.
