### ISSUE TITLE
bug: text overflows in channel dropdown

### ISSUE THREAD

**Issue by amycatgirl** [ubuntu/app-center#1472]
![Screenshot of Ubuntu App Centre's channel selection dropdown](https://github.com/ubuntu/app-center/assets/138383945/b400639e-7ef5-4292-bfa1-0c4d9e8b66e9)

I think the title and the screenshot are pretty self-explanatory. Looks like there isn't enough height for the text to fit properly.

The app inside the screenshot is Darktable.

**Comment by d-loose** [comment]
Thanks for the bug report - this is likely related to #1473.
