### ISSUE TITLE
Sort by dropdown not showing properly 

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1473]
**tracking:    latest/edge**
![image](https://github.com/ubuntu/app-center/assets/2129497/ea25bc47-f23f-4dd1-9e93-abd03e90d5e6)

**Comment by d-loose** [comment]
Thanks for spotting this. Seems to be caused by updating to the latest version of yaru, specifically https://github.com/ubuntu/yaru.dart/pull/383.
Needs a fix in either yaru or ubuntu_widgets.
