### ISSUE TITLE
A shortcut for searching

### ISSUE THREAD

**Issue by Master811129** [ubuntu/app-center#1475]
Please add a keyboard shortcut to easily make the search-bar focused. `ctrl+f` or just `/` would do it. 

Or even better, search bar gets focused as we type.

**Comment by amardhruva** [comment]
+1 typing anywhere(atleast on the home screen) should bring search to the forefront. Other app stores already do this and reduces the actions taken by user to install an app.

**Comment by itay-grudev** [comment]
Please add both `Ctrl+F` and `Ctrl+L` for searching - the latter being the nautilus shortcut so it feels more like home.

**Comment by mccoys** [comment]
It is not even possible to >tab through the menu or search bar.  The only way to get to the search bar is using the mouse which is not very coherent with other ubuntu ui.

IMO the best shortcut would be to directly type anything to start searching.

**Comment by BLKKKBVSIK** [comment]
We should add a `FocusNode` that get requested with `.requestFocus()` when using the shortcut. The shortcut can be registered using this [method](https://docs.flutter.dev/ui/interactivity/actions-and-shortcuts)

**Comment by Master811129** [comment]
Thanks for the consideration.

**Comment by itay-grudev** [comment]
@d-loose Is it possible there is a regression on this? `Ctrl+F` stopped working for me.

**Comment by d-loose** [comment]
The keyboard shortcut works for me on both `latest/edge` and `latest/stable/ubuntu-24.04`. Is it a reproducible issue for you?

**Comment by itay-grudev** [comment]
Yhea. Something is wrong. It worked fine on `23.10` before I upgraded but now on `24.04` it's definitely not working.

**Comment by d-loose** [comment]
Hm, weird - I double checked the versions in the channels I mentioned and see no problems there. Could you open a separate issue for that and provide the output of `snap info snap-store` along with any relevant logs from `$HOME/snap/snap-store/current/.local/share/snap-store/` if there are any? Thanks!
