### ISSUE TITLE
Snapd exception shown when connection timeout

### ISSUE THREAD

**Issue by tim-hm** [ubuntu/app-center#1479]
When trying to browse the app center without an internet connection this error was surfaced. We should fail more gracefully here.

@anasereijo @d-loose 

<img width="1358" alt="SCR-20231101-spgu" src="https://github.com/ubuntu/app-center/assets/1335525/f30e06f1-5109-4318-a1cd-002ff4036db2">

**Comment by dishankjindal1** [comment]
Hi @BLKKKBVSIK - I would like to pick up the issue and give it a try. Can you give me hint on where should I look for this issue? And how do I emulate it?

**Comment by BLKKKBVSIK** [comment]
Hi @dishankjindal1 

You simply have to run the project without being connected to internet.
One good way to fix it, is to catch this error and display a generic text like "No connection or couldn't connect"
Don't hesitate if you need more instructions.

**Comment by anasereijo** [comment]
@BLKKKBVSIK After getting connection back, will users need to reload the app, or will it update automatically?

**Comment by anasereijo** [comment]
For copy, I think it should read - We can't load content in the App Center without an internet connection.

One cool thing we could do is to use the animated icon as suggested [here](https://github.com/ubuntu/app-center/issues/1432#issuecomment-1752160392) :)

Thanks for your help @dishankjindal1 !

**Comment by BLKKKBVSIK** [comment]
> @BLKKKBVSIK After getting connection back, will users need to reload the app, or will it update automatically? 

For now, the user will need to reload the tab at least. But in the case where the device has no internet connection, we could refresh it automatically in a second time.

**Comment by tim-hm** [comment]
When offline, we could show a modal or screen to prevent users from interacting with the app. This avoids the complexities of handling numerous corner cases that arise when users navigate the app without an internet connection. The modal could include a 'retry' button and perform periodic connectivity checks, effectively freezing the app until internet is available.

**Comment by anasereijo** [comment]
Could we have two solutions for two different scenarios?

### a) user is using the app and then the internet disconnects:
I think we should show an error message within the page they had opened: 

We can't load content in the App Center without an internet connection. 
Check your connection and reload.
[Retry]

this way, once the connection is back, the user will see the page they were looking at before, or the page they were trying to open, so they don't lose the 'flow'.



### b) user is offline and tries to open the app
have @tim-hm's approach of having a modal preventing users from interacting with the app. the window will be empty (dark or light depending on the user's theme)

**Unable to connect to the App Center**
Check your connection and reload.
[Retry]

some inspiration for the second use case:

<img width="1333" alt="Screenshot 2023-12-13 at 12 03 25" src="https://github.com/ubuntu/app-center/assets/36884067/3ba16477-62b2-4031-93c2-14352bb9fb0c">

**Comment by kenvandine** [comment]
I recently ran into this issue where the device was online but on a network
that didn't allow access to the snap store.  It's an odd case, but the only
place I saw the exception was the app details view.  The more frustrating
behavior was the discovery experience, trying to browse categories all
listed the same apps. No indication it couldn't fetch the content from the
store and even worse, once on a proper network the categories were still
incorrect and the app data had to be purged to browse content.  I guess it
cached some incorrect data.

**Comment by dishankjindal1** [comment]
Hey, I am having trouble setting up the environment.

Can you give me detailed steps? Sorry, but i tried to do it myself and i need assistance now.

Currently i have macbook pro m2, and i installed UTM virtual machine and installed ubuntu 22LTS on it.

**Comment by tim-hm** [comment]
@dishankjindal1 have you tried the steps in [contributing.md](https://github.com/ubuntu/app-center/blob/main/CONTRIBUTING.md#contributing-to-the-code)?

In the past I've found running these apps in an apple silicon VM tricky but hopefully the experience has improved :crossed_fingers:

**Comment by tim-hm** [comment]
> Could we have two solutions for two different scenarios?

@anasereijo maybe we pause until we've had time to think through the design for handling offline?

**Comment by anasereijo** [comment]
> @anasereijo maybe we pause until we've had time to think through the design for handling offline?

Agree, the whole offline experience needs more thinking, but I think that in the meantime it is important to tell the users what's going on somehow

**Comment by spydon** [comment]
Fixed by #1723
