### ISSUE TITLE
create Split button

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1491]
I believe this also has to be added on Yaru, right @Feichtmeier @d-loose  ?

App page:

<img width="576" alt="Screenshot 2023-11-14 at 14 32 20" src="https://github.com/ubuntu/app-center/assets/36884067/2d948e2c-52d6-47e7-9357-8c8dcf347b99">

**Comment by Feichtmeier** [comment]
> I believe this also has to be added on Yaru, right @Feichtmeier @d-loose  ?
> 
> App page:
> 
> <img width="576" alt="Screenshot 2023-11-14 at 14 32 20" src="https://github.com/ubuntu/app-center/assets/36884067/2d948e2c-52d6-47e7-9357-8c8dcf347b99">
> 

Looks like a nice general purpose widget so I would say yes, good addition to yaru widgets 👌

**Comment by anasereijo** [comment]
@BLKKKBVSIK is this something you can do and then propose to yaru widgets? Thank youu

**Comment by BLKKKBVSIK** [comment]
On it :)

**Comment by anasereijo** [comment]
closing as this is being tracked here: https://github.com/ubuntu/app-center/issues/1776
