### ISSUE TITLE
Unable to update Snap Store

### ISSUE THREAD

**Issue by Supermarcel10** [ubuntu/app-center#1509]
Cannot update the snap store through the snap store because ubuntu-software snap-store is running.
There doesn't seem to be any other UX friendly way of updating except via CLI.

![image](https://github.com/ubuntu/app-center/assets/47798787/6b2f83cc-b97c-4b33-a63a-190bc03813f4)
![image](https://github.com/ubuntu/app-center/assets/47798787/043ef6e6-ff15-4a11-96eb-7b08300a3d70)

![image](https://github.com/ubuntu/app-center/assets/47798787/20492c71-3929-4682-9956-a8e80f377bd4)

**Comment by matthew-hagemann** [comment]
Hi @Supermarcel10,

Definitely not a good UX for refreshing / switching channels. Its a unique case in that it trying to update itself, and we will probably need a special case specifically for making changing to the App Centers' snap via the App Center.

Thank you for the issue post!

**Comment by anasereijo** [comment]
We removed the App Center update from the listing and added instead an info banner whenever there's an update for it. That info banner provides instructions on how to update the App Center and a button to quit and update the application. 

https://github.com/ubuntu/app-center/pull/1751
