### ISSUE TITLE
'Change channel' shown in 2 lines

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1513]
Hi,

![image](https://github.com/ubuntu/app-center/assets/23138504/2949f84d-8b84-4354-b1c5-060d17a3e1ea)

Could be better in 1 line only, FR version here.

**Comment by matthew-hagemann** [comment]
Hi @fthx, thanks for reporting this! 

Feels like instead of doing a text wrap and spanning it over two lines we should swap to cutting off lines with an ellipsis if we run out of screen space. (ie: `Changer de can...`) @anasereijo?

**Comment by fthx** [comment]
Ellipsis does not look great, IMO.
![image](https://github.com/ubuntu/app-center/assets/23138504/070acfc7-a4fa-4e1f-a93d-1e129e6cefbf)
Here we have some place for a longer string, because reducing the width shows another layout:
![image](https://github.com/ubuntu/app-center/assets/23138504/0da367b4-c255-456a-943a-062470e015c2)
where there is a lot of place for change-channel string.

**Comment by BLKKKBVSIK** [comment]
> Can we resize the button according to the text length?

We can, but on long text, it will break the UI on the smallest breakpoint. Or we can cut the text off with an ellipsis only on the smallest breakpoint.

**Comment by anasereijo** [comment]
>  Or we can cut the text off with an ellipsis only on the smallest breakpoint.

That sounds good! I suppose there will be a tooltip on hover to tell the user the full label?

**Comment by fthx** [comment]
Means that the label will not be fully displayed?
Sorry, I don't understand this regression here.

**Comment by BLKKKBVSIK** [comment]
> Means that the label will not be fully displayed? Sorry, I don't understand this regression here.

The label will try to be displayed fully, but depending on the window size, there might be an ellipsis with a tooltip.

**Comment by fthx** [comment]
Ok.
But the point I do not understand is that when the window's width is low, the "Change channel" label comes above the main info row.
![image](https://github.com/ubuntu/app-center/assets/23138504/cb56b6e8-3d7b-4676-8397-e2ceb06cd190)
So it seems there's not really a label's width issue?

**Comment by fthx** [comment]
I don' t understand the eyes.

In fact, there is a wider probleme IMO here:
![image](https://github.com/ubuntu/app-center/assets/23138504/0509c286-8793-448c-8944-7138e5476930)
There are two labels (package, channel/open) those widths are not dynamically set and there is a lot of space left to not ellipsize any of them.

**Comment by BLKKKBVSIK** [comment]
The eye emoji means that we will look into this.
I agree with you, the buttons with should depend on the length of their text.
