### ISSUE TITLE
Icon for Adwaita theme

### ISSUE THREAD

**Issue by Fabioamd87** [ubuntu/app-center#1514]
Dears,
I'm using Ubuntu 23.10 with Adwaita (Default) theme.
using this theme I see a generic icon for App Center.
Who needs to create a dedicated icon for this application?
Thanks!

![immagine](https://github.com/ubuntu/app-center/assets/284733/75d248ed-eb4b-4c99-b1d2-f1e9719915c7)

**Comment by anasereijo** [comment]
Hi @Fabioamd87, thanks for submitting this issue.
We should display the App Center icon indeed. @d-loose do you know why this is happening?

**Comment by Fabioamd87** [comment]
not sure what this last comments means :)

**Comment by BLKKKBVSIK** [comment]
That this is not the correct behavior, we are working on fixing that :)
