### ISSUE TITLE
FEAT: While runnng project on local system i'm getting "fatal error: 'cairo/cairo.h' file not found" Error #1460

### ISSUE THREAD

**Issue by Cevedale** [ubuntu/app-center#1516]
you should install Cairo on your Ubuntu system:
sudo apt-get install libcairo2-dev

verify that your Flutter project has the correct dependencies specified in the 'pubspec.yaml' file.
dependencies:
cairo: ^0.9.0

update Flutter and FVM

**Comment by BLKKKBVSIK** [comment]
Duplicate of #1460
