### ISSUE TITLE
Void debian package window

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1521]
Hi,

- search for "pychess" in search bar
![image](https://github.com/ubuntu/app-center/assets/23138504/9e4d51bb-3aff-42aa-938f-4c1f1b0fc120)

- click on PyChess
![image](https://github.com/ubuntu/app-center/assets/23138504/dba1f97f-c4f1-4118-9a2b-1f44b93a25ca)

- problem ;-)
![image](https://github.com/ubuntu/app-center/assets/23138504/18a11b29-170a-4894-b448-e96225ae7baf)

**Comment by fthx** [comment]
Happens only using v1069 (edge) not v1046 (ubuntu-24.04).

**Comment by BLKKKBVSIK** [comment]
This is due to the package info returning null.
Nonetheless, the UI shouldn't render like so.
