### ISSUE TITLE
loading status when opening the App Center

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1528]
I get a white screen when opening the app. We should have a spinner and below it text "Loading the App Center..."

**Comment by BLKKKBVSIK** [comment]
It's probably due to GDK Window initialization. Got to investigate deeper.

**Comment by BLKKKBVSIK** [comment]
Cannot do anything from the Flutter side of things.
We have a minimal time when Flutter is initializing and the GTK Window is already open.

**Comment by sminez** [comment]
@BLKKKBVSIK even if there's nothing we can do from the Flutter side is there maybe something we can do on the desktop/GTK side? Presumably this is then an issue for all desktop Flutter apps running on GTK and not just the App Center

**Comment by anasereijo** [comment]
@sminez so if possible, it would be great to have a solution even if most of the time it's a minimal loading time. I remember that when it happened it was quite long wait (I was using a VM).

**Comment by BLKKKBVSIK** [comment]
I'm not sure if that's something we want to fix.
On average hardware, it's only 1 or 2 frames, I don't think adding a loading state will be noticeable.
