### ISSUE TITLE
manage: users can't cancel updates

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1533]
<img width="1042" alt="Screenshot 2023-12-13 at 16 58 30" src="https://github.com/ubuntu/app-center/assets/36884067/209bec3d-d5d0-442a-b87a-fa1e7f2933d2">

currently, the users can't cancel the updates after clicking on [update all]. we should offer that option.

screenshots (also on figma)
<img width="1240" alt="Screenshot 2023-12-13 at 16 58 55" src="https://github.com/ubuntu/app-center/assets/36884067/aaa32bbc-e14b-419e-881b-450af771c83b">

**Comment by codinesh** [comment]
Hello @anasereijo, @BLKKKBVSIK, I would like to work on this one and created PR to fix this. Please let me know if you have any suggestions. 

Also, I couldn't find any option to request reviews, please help with the review request.

**Comment by BLKKKBVSIK** [comment]
Hi @codinesh 
Ana is on leave, I'll review your PR on Monday if that's OK for you.

**Comment by codinesh** [comment]
> Hi @codinesh 
> Ana is on leave, I'll review your PR on Monday if that's OK for you.

Sure, please take your time @BLKKKBVSIK. Thank you.
