### ISSUE TITLE
New icon for GNOME Console

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1543]
Hi,

Just had switched to the new GNOME Terminal app (gnome-sonsole) and I see this icon:
![image](https://github.com/ubuntu/app-center/assets/23138504/b77f1056-6f37-4e6f-84d0-b48339cd1c44)
Is there a new one under the hood?
I feel this (adwaita's) one quite outdated vs the GNOME Terminal Yaru's icon.

**Comment by BLKKKBVSIK** [comment]
Is it the default icon for any application on your theme? 
It feels like #1514

Let me know if this is a different issue, otherwise I will close this one.

**Comment by fthx** [comment]
Non that's just Adwaita's icon.
Not a bug, just a styling issue.
I don't know if Console will be the new default terminal app in Noble.

**Comment by BLKKKBVSIK** [comment]
I misread your issue.

Your issue is not in the right repository, since it's about the Terminal app.
Will get back to you once I know to which repository this issue needs to be moved.

**Comment by spydon** [comment]
The request for another icon for Gnome Console should probably go in their repository:
https://gitlab.gnome.org/GNOME/console
Or just change it locally to the same icon as Gnome terminal uses:
https://www.solvetechnow.com/post/how-to-change-app-icon-in-ubuntu?utm_content=cmp-true

As far as I know we don't set icons for non-default applications.

**Comment by BLKKKBVSIK** [comment]
Since the issue wasn't about the App Center, I'll close it.

**Comment by fthx** [comment]
Yep, I really don't know why I posted this here rather than Yaru's repo!!
