### ISSUE TITLE
Flameshot App fails to install

### ISSUE THREAD

**Issue by ltai0001** [ubuntu/app-center#1548]
Hello
trying to install Flameshot App from the App Center but it fails to install. Clicking on the green install button doesnt do anything
App Center version 1.0.0-alpha
OS: Ubuntu 23.10

**Comment by BLKKKBVSIK** [comment]
Hi @ltai0001 
Do you have any error or any logs?

**Comment by ltai0001** [comment]
> Hi @ltai0001 
> 
> Do you have any error or any logs?

No apparent error shows up. Is there a log file I can look at to check?

**Comment by ltai0001** [comment]
File is empty when I open. Is there another one I can look at?

**Comment by Feichtmeier** [comment]
If this issue also happens when you install it in the terminal with `sudo snap install flameshot` then this is an issue for the flameshot repository and not here @ltai0001

**Comment by soumyaDghosh** [comment]
The flameshot snap is essentially broken. The content snap it depends on is not available anymore.

```bash
 soumyaxubuntu  soumyas-gf63-thin-11uc  ~  sudo snap install flameshot
[sudo] password for soumyaxubuntu:          
error: cannot perform the following tasks:
- Ensure prerequisites for "flameshot" are available (cannot install prerequisite "kde-frameworks-5-91-qt-5-15-3-core20": no snap revision available as specified)
```

**Comment by soumyaDghosh** [comment]
@ltai0001 kindly report it here

https://github.com/flameshot-org/flameshot/blob/master/snapcraft.yaml

**Comment by BLKKKBVSIK** [comment]
If that's a snap issue, and not an App Center issue, I'll close this issue.

**Comment by soumyaDghosh** [comment]
@BLKKKBVSIK still there should be a popup to explain yhe problem to yhe user.

**Comment by ltai0001** [comment]
@soumyaDghosh totally agree. Something should alert the user...

**Comment by soumyaDghosh** [comment]
> @soumyaDghosh totally agree. Something should alert the user...

Actually it's complicated, there's a method to alert about error, but snapd doesn't show this as error, it actually shows success. You can check this by running the app from terminal. So, work needs to be done on the `snapd.dart`.

**Comment by ltai0001** [comment]
BTW I get the same error as @soumyaDghosh when I try `sudo snap install flameshot`

`error: cannot perform the following tasks: - Ensure prerequisites for "flameshot" are available (cannot install prerequisite "kde-frameworks-5-91-qt-5-15-3-core20": no snap revision available as specified)`

**Comment by workmailrahul** [comment]
sudo snap install flameshot

error: cannot perform the following tasks:
- Ensure prerequisites for "flameshot" are available (cannot install prerequisite "kde-frameworks-5-91-qt-5-15-3-core20": no snap revision available as specified)

i got this when i try to install flamethot with snap
