### ISSUE TITLE
Manage Page not updating after refresh of snaps

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1555]
[Screencast from 2023-12-31 01-02-36.webm](https://github.com/ubuntu/app-center/assets/72045785/7514c326-4d4b-4027-a8df-89c5ec4f7a54)

**Comment by anasereijo** [comment]
Hi @soumyaDghosh apologies for such a late reply. Is this still an issue for you?

**Comment by soumyaDghosh** [comment]
> Hi @soumyaDghosh apologies for such a late reply. Is this still an issue for you?

Sorry it's fixed now!
