### ISSUE TITLE
Manage page: button content aligment is not consistent

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#1558]
![grafik](https://github.com/ubuntu/app-center/assets/15329494/da294c10-07b1-4211-ba24-d50d987e0ed0)

In the top control panel with the "update all button" the button height is correct and thus the content padding matches and thus the content is positioned in the middle.
However in those containers with the border, it looks like the button height is a little bit squeezed and thus the content padding is too much for the content and thus the content is positioned a little bit too much down
May be an optical illusion but I am almost certain :crossed_fingers:

**Comment by soumyaDghosh** [comment]
just to add, the `update` and `open` words aren't positioned properly.

![image](https://github.com/ubuntu/app-center/assets/72045785/6925784f-6357-4d72-bc2a-16bbf64efdc4)
