### ISSUE TITLE
Enhancement: A more gnome like titlebar

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1562]
![Screenshot from 2024-01-07 20-51-25](https://github.com/ubuntu/app-center/assets/72045785/239e520c-d2c1-4e56-8add-edd0108315d8)
![Screenshot from 2024-01-07 20-51-20](https://github.com/ubuntu/app-center/assets/72045785/4906fde8-e3bb-4ef3-9a6c-a8a3c3e1bc4c)

I was not able to implement the titlebar in the snap_page, but, I don't think it's tough.

@anasereijo @BLKKKBVSIK thoughts?

**Comment by anasereijo** [comment]
@soumyaDghosh apologies for taking so long to reply — we have been busy with high priority projects. Thanks for sharing this! 
I quite like the direction of it, and it's definitely more consistent with other applications. I think we should add a border bottom in the title bar, though. What do you think?

**Comment by soumyaDghosh** [comment]
> I think we should add a border bottom in the title bar, though. What do you think?

I don't think it'll anyways look good

![image](https://github.com/ubuntu/app-center/assets/72045785/636b810d-c7f9-476b-9d11-cf4e79fe3049)

this is the settings app for example.

Also, in the apps page, as I was discussing this @Feichtmeier, we can remove the header space and add the back button to the titlebar itself.
