### ISSUE TITLE
Enhance the Games Tab

### ISSUE THREAD

**Issue by ashuntu** [ubuntu/app-center#1563]
Right now the Games tab in the App Center is just a procedural page based on app category, but it could serve as a useful hub for gaming related apps, information, and tools.

@jssotomdz, @ZoopOTheGoop, and I would like to make a dedicated Games tab that provides more information than just lists of apps. Our initial ideas include a featured carousel of games and apps (think [Steam's carousel of games](https://store.steampowered.com/)), "packs" that include apps and games that often are used together (like Steam + Discord + OBS + etc.), and more robust headings similar to the Explore page like Top 10 apps/games, "Hot" apps/games, etc.

Additionally, we could query what games/apps someone already has installed, and recommend others. Like if you have Steam installed but not Discord, etc.

Gaming on Linux can be daunting for newcomers, so, approval permitting, we'd also like to include links to external resources that may not be controlled by Canonical or Ubuntu. This could include helpful resources like [ProtonDB](https://www.protondb.com/), [Lutris](https://lutris.net/), [Heroic](https://heroicgameslauncher.com/), [Wine](https://www.winehq.org/), etc.

These are all goals that could take suggestions or criticism, so feel free to comment thoughts.

**Comment by soumyaDghosh** [comment]
The games tab can be made like a completely separate page, and so does the other tabs, IMO. Like eg: play-store in android, it shows big screenshots of games, shows ongoing events, like an event going on epic-store right now, can be shown there, which can they be played by using heroic, which is currently not yet available properly as a snap, but will be soon.

**Comment by michaldev** [comment]
> The games tab can be made like a completely separate page, and so does the other tabs, IMO. Like eg: play-store in android, it shows big screenshots of games, shows ongoing events, like an event going on epic-store right now, can be shown there, which can they be played by using heroic, which is currently not yet available properly as a snap, but will be soon.

In my opinion, it is too complicated and requires too much from developers. Many package developers have no control over the game code at all.

The thread author's proposal is more reasonable. A list of useful tools and a description of what they can be used for will be a hit for people who are not familiar with the Linux application ecosystem.
