### ISSUE TITLE
The website doesn't opens the store page

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1571]
Clicking on view in desktop store makes this for any snap

![image](https://github.com/ubuntu/app-center/assets/72045785/fcaaae79-635d-4ae4-ad1d-867c8dc9ec2e)

**Comment by d-loose** [comment]
I can't reproduce this issue. Does this still happen for you? Could you provide any logs (`~/.local/share/snap-store/`, `journalctl -b -g snap-store`) if available?

**Comment by soumyaDghosh** [comment]
Yes, not sure when, but this seems to have been fixed. :tada:
