### ISSUE TITLE
Window does not identify itself appropriately

### ISSUE THREAD

**Issue by bluesabre** [ubuntu/app-center#1581]
Similar: https://github.com/canonical/firmware-updater/issues/257

Using Xubuntu 24.04. When opening "App Center" from the menu, the window does not set it's name in a way the window manager understands. See the attached screenshot, where snap-store and gnome-mahjongg are installed as snap packages. gnome-mahjongg sets a window title (Mahjongg) while snap-store does not.

Unlike firmware-updater, snap-store does set it's icon in a way the window manager understands.

![Screenshot_xubuntu24 04-2_2024-01-21_06:09:00](https://github.com/ubuntu/app-center/assets/1894517/1fda4aa0-88f5-41f3-b13e-6f94fa415507)

**Comment by d-loose** [comment]
Fixed in #1534

**Comment by bluesabre** [comment]
Confirmed that the window name is being set correctly now.
