### ISSUE TITLE
Bug: Search doesn't seem to be optimized

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1584]
In the snap store, today, I tried to search my own [app](snapcraft.io/menukaran). It's a desktop file editing app. But, when I search with keywords `desktop file edit` or related searches I get these in the search results

![image](https://github.com/ubuntu/app-center/assets/72045785/b31022cc-8e7e-4414-b633-ddcf5316328f)

![image](https://github.com/ubuntu/app-center/assets/72045785/e733ca94-2564-4ec0-bc27-b245ab18057b)

![image](https://github.com/ubuntu/app-center/assets/72045785/d0c5189f-28b0-4217-a407-8e9045b12b7e)

None of the first 5-6 apps, except the `gnome-text-editor` is meant to edit desktop files. Am I doing something wrong, or is this some kind of bug?

**Comment by d-loose** [comment]
app-center doesn't handle any search logic for snaps - the results that you see here come from the snapd API and are the same that you would get from `snap find "desktop file edit"`, etc.
