### ISSUE TITLE
Window sets invalid icon name

### ISSUE THREAD

**Issue by bluesabre** [ubuntu/app-center#1604]
The App Center window no longer shows an icon and seems to be setting an invalid icon name. See related `xprop` output:

```
WM_ICON_NAME(STRING) = "App Center"
_NET_WM_ICON_NAME(UTF8_STRING) = "App Center"
```

![image](https://github.com/ubuntu/app-center/assets/1894517/b35e0a41-d813-4060-953b-39e23b6edca2)

**Comment by Feichtmeier** [comment]
This should be fixed by now
