### ISSUE TITLE
Confusing "Manage" tab description

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#1607]
Hi,

![image](https://github.com/ubuntu/app-center/assets/23138504/9bf74710-6a6a-4751-9a26-0553f41eb97a)

I find this not that clear.
*I* know that App Center does only manage snaps.
But for a new user it's not clear that "manage my apps" means "manage only my snaps apps" even if App Center can find and install debs.

So we could change that mentioning that App Center manages snap apps in this tab.

**Comment by antonkesy** [comment]
![image](https://github.com/ubuntu/app-center/assets/25124866/59eaa087-e1fd-49fb-bd66-ff8098c2990e)

English version of the screenshot

**Comment by anasereijo** [comment]
Thanks for filing the issue @fthx. This was recently updated (https://github.com/ubuntu/app-center/pull/1720).
