### ISSUE TITLE
Snap Store not showing icons of snaps published by me

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1646]
The snap store is not showing icons of snaps published by me in the installed tab. This issue was first shared to me by @Feichtmeier, later when I got back my lappy, I also saw the same. The icons are showing up fine in the store, then what's wrong am I doing. Kindly shred some light on this, anyone.

![image](https://github.com/ubuntu/app-center/assets/72045785/f3b6de0d-6348-4c51-9e3e-0e5414f64917)

**Comment by d-loose** [comment]
Icons for all of those snaps are showing fine for me. Maybe it's a caching issue? Does deleting `~/snap/snap-store/common/.cache/` resolve the issue?

**Comment by soumyaDghosh** [comment]
Nope still the same, the icons are showing, when I am searching for those snaps, but not particularly in the installed tab.

**Comment by Feichtmeier** [comment]
I dont think this is anyhow related to this app
:D 
bad anyhow, my problem was rather that they dont show up in the dock after you opened them
I guess testing if this happens with the command line (pretty sure) would close this issue on this repo

**Comment by Feichtmeier** [comment]
Yeah i think this is not related to this project, @d-loose feel free to re-open if you disagree
