### ISSUE TITLE
Upgrade from 23.10 to 24.04 doesn't change pc-kernel channel on TPM FDE version

### ISSUE THREAD

**Issue by poshul** [ubuntu/app-center#1647]
I just upgraded from 23.10 to 24.04 on a system using the snap packaged kernel. The upgrade did not install the newer kernel, and checking the store after the upgrade it's still tracking 23.10/stable rather than 24/stable.

**Comment by d-loose** [comment]
Thanks for the bug report! This isn't related to the App Center though - I suppose the most relevant bug for this is here: https://bugs.launchpad.net/ubuntu/+source/shim/+bug/2062373
