### ISSUE TITLE
Simplified Chinese cannot be displayed

### ISSUE THREAD

**Issue by qwer130140190** [ubuntu/app-center#1658]
Simplified Chinese cannot be displayed，24.04 arm64
![WX20240427-214530@2x](https://github.com/ubuntu/app-center/assets/29937512/c175180a-1cba-4076-b13a-d9cf0eb9fe3d)

**Comment by qwer130140190** [comment]
This should be a typical issue with Flutter on the ARM platform, as the installation program during system installation also cannot display Chinese. I have also found some similar issues with Flutter on ARM in Google.

**Comment by d-loose** [comment]
> This should be a typical issue with Flutter on the ARM platform, as the installation program during system installation also cannot display Chinese. I have also found some similar issues with Flutter on ARM in Google.

Thanks for your report - unfortunately there's nothing we can do about this here. Upstream issue: https://github.com/flutter/flutter/issues/90951.
