### ISSUE TITLE
Search with a "Filter by" of "Debian packages" not working in "snap-store" version "0+git.97116aa" Rev. 1134

### ISSUE THREAD

**Issue by ricmarques** [ubuntu/app-center#1685]
Ubuntu MATE 24.04 LTS ("Noble Numbat") was released with the following "App Center" version:

snap-store
Version: 0+git.1419621
Rev: 1124

In that version of "App Center" / "snap-store", if I open "App Center" and do a Search for, let's say, "**gparted**" in the top "Search for apps" textbox, the search initially returns "**No results found for "gparted"**" because the "**Filter by**" dropdown list defaults to the option "**Snap packages**". However, if I change the "Filter by" selected option to "**Debian packages**", then the search results area **correctly** shows the "GParted Partition Editor" box.

Now, the problem happens if "App Center" gets (automatically) updated to the following version:

snap-store
Version:  0+git.97116aa    
Rev: 1134

In that version of "snap-store", the same search for "gparted" then **incorrectly** returns "_No results found for "gparted"_" even if we change "Filter by" dropdown list selected option to "Debian packages".

Is this a known issue / bug?

**Comment by d-loose** [comment]
Thanks for the report - I suspect you see something like this when running `snap-store` from the terminal:

```
[ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
FormatException: Unknown url type 'vcs-browser'
```

A fix for this is underway https://github.com/canonical/appstream.dart/pull/30

**Comment by ricmarques** [comment]
Hi, @d-loose (Dennis Loose) :slightly_smiling_face: 

You wrote:

> Thanks for the report - I suspect you see something like this when running `snap-store` from the terminal:
> 
> ```
> [ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
> FormatException: Unknown url type 'vcs-browser'
> ```
> 
> A fix for this is underway [canonical/appstream.dart#30](https://github.com/canonical/appstream.dart/pull/30)

Thank you very much for your very quick and encouraging reply :slightly_smiling_face:  I confirm that, when I run `snap-store` from the terminal, I get the errors you've mentioned in your reply (and some additional errors):

```bash
ricmarques@ubumate2404vm:~/Desktop$ snap-store
Gtk-Message: 23:14:21.313: Failed to load module "appmenu-gtk-module"
Gtk-Message: 23:14:21.315: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(snap-store:2874): Gtk-WARNING **: 23:14:21.344: GTK+ module /snap/snap-store/1134/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 23:14:21.344: Failed to load module "canberra-gtk-module"

(snap-store:2874): IBUS-WARNING **: 23:14:21.433: Failed to mkdir /home/ricmarques/snap/snap-store/1134/.config/ibus/bus: Not a directory
flutter: INFO snap-store: Logging to /home/ricmarques/snap/snap-store/1134/.local/share/snap-store/snap-store.log
[ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
FormatException: Unknown url type 'vcs-browser'
#0      _parseUrlType (package:appstream/src/collection.dart:931)
#1      new AppstreamCollection.fromYaml (package:appstream/src/collection.dart:490)
#2      AppstreamPool._loadYamlCollectionInIsolate (package:appstream/src/pool.dart:94)
<asynchronous suspension>

** (snap-store:2874): WARNING **: 23:14:47.228: atk-bridge: get_device_events_reply: unknown signature
`
