### ISSUE TITLE
vs code 1.90 not working after update from snap store

### ISSUE THREAD

**Issue by aravindjaga6** [ubuntu/app-center#1691]
yesterday i updated my code 1.90 through snap app center after that it's not working but installing through the deb package it working fine. It seems like there is a bug in latest version in snap center.

**Comment by Rexogamer** [comment]
this is not a bug with the App Centre - this is an upstream issue with VSCode itself which will be fixed in the next release (see https://github.com/microsoft/vscode/issues/212494).
