### ISSUE TITLE
Contact [Developer] link does not work for some apps

### ISSUE THREAD

**Issue by thatLeaflet** [ubuntu/app-center#1692]
For some apps, the link to contact the developer does not work. For example, it does not work for the OBS Studio snap.

However, it works for other snaps, such as the Firefox snap.

![Screenshot from 2024-06-10 09-38-01](https://github.com/ubuntu/app-center/assets/80165419/cd2ba214-aad9-4ff6-8cfb-5d2f85a08e3f)

**Comment by d-loose** [comment]
Thanks, looks like the snap metadata can contain empty strings for the URLs.
