### ISSUE TITLE
App centre does not inherit dark theme

### ISSUE THREAD

**Issue by elChupaNibre** [ubuntu/app-center#1714]
All other snaps installed adhere to the Adwaita Dark GTK theme I'm using on Xubuntu 24.04 (normal, not minimal install), but I cannot for the life of me get the app centre to behave in the same way. It's almost blindingly bright when I open it after being accustomed to using dark themed apps. 

![Screenshot_2024-06-22_15-36-29](https://github.com/ubuntu/app-center/assets/13789765/2584734b-301c-47e8-8850-cdd8730a1a03)

**Comment by d-loose** [comment]
This is either a bug in Xubuntu/Xfce or the Flutter engine. The theme brightness is determined via the desktop portal (see [here](https://github.com/flutter/engine/blob/be7db94196fee940e319363f7ed0c486a780ae50/shell/platform/linux/fl_settings_portal.cc)).
Maybe @robert-ancell knows more :)

**Comment by robert-ancell** [comment]
Right, I suspect this might be an issue with the way Xubuntu is reporting the theme. If this occurs with all Flutter apps on your system then file against https://github.com/flutter/flutter/
