### ISSUE TITLE
[Touch] Scrolling does not work

### ISSUE THREAD

**Issue by cm-t** [ubuntu/app-center#1732]
Hi,

On a Ubuntu (gnome-shell) 24.04 LTS installation (Tablet StarLite from starlabs). App-center up to date.

Expected:
 * I open an apps
 * I need to scroll
 * I use touchscreen to scroll
 * works

Result on app-center:
 * I open app-center
 * I browser categories, or search result; I need to scroll
 * I use touch screen (_1 finger like I do in gnome apps or firefox_)
 * does not work
     * Then I try 2 finger scroll
         *  still not works
         
Current user workaround:
 * put finger on the right side of the screen
 * scroll bar appears
 * drag and drop it
     * with small touch area of it, and its infinite scroll (_search result)_ it is not a good UX

**Comment by Feichtmeier** [comment]
I think we need to add this to MaterialAPp

scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: {
          PointerDeviceKind.mouse,
          PointerDeviceKind.touch,
          PointerDeviceKind.stylus,
          PointerDeviceKind.unknown,
          PointerDeviceKind.trackpad,
        },
      ),

I think we already have an issue for this somewhere

**Comment by spydon** [comment]
Fixed in #1791
