### ISSUE TITLE
GNOME Tweaks not appearing in search results in App Center despite being installed

### ISSUE THREAD

**Issue by dharshinipalani** [ubuntu/app-center#1736]
**Bug Description:**
I have encountered an issue where GNOME Tweaks does not appear in the search results in App Center. Additionally, after installing GNOME Tweaks, it does not show up in the list of installed applications.

**Steps to Reproduce:**

1. Open App Center.
2. Search for "Tweaks."
3. Observe that GNOME Tweaks does not appear in the search results.
4. Install GNOME Tweaks (if not already installed).
5. Check the list of installed applications in App Center.
6. Observe that GNOME Tweaks is missing from the installed applications list.

**Expected Behavior:**
GNOME Tweaks should appear in the search results when searching for "Tweaks" in App Center. Additionally, once installed, it should be listed among the installed applications.

**Actual Behavior:**
GNOME Tweaks does not appear in the search results and is not listed among the installed applications even after installation.

**System Information:**

OS: Ubuntu 24.04 LTS
App Center version:1.0.0
GNOME Tweaks version: [46.0
**Additional Information:**
search results
![Screenshot from 2024-07-11 11-16-51](https://github.com/ubuntu/app-center/assets/123818001/ca6a15b4-70c3-48e2-acb8-50b9c5e307c6)
Installed Application
![Screenshot from 2024-07-11 11-24-06](https://github.com/ubuntu/app-center/assets/123818001/77e34ca1-fd1b-4268-a2aa-f9466d6c68b9)
![Screenshot from 2024-07-11 11-24-42](https://github.com/ubuntu/app-center/assets/123818001/67c839da-e60c-438a-9894-d8417fa289c3)

**Comment by d-loose** [comment]
GNOME tweaks is only available as debian package, it'll appear in the search results when you adjust the filter accordingly and can be installed from there. The manage page only lists snap packages - we're planning to clarify this in the UI.
