### ISSUE TITLE
Unknown error in UI for canceled authentication

### ISSUE THREAD

**Issue by antonkesy** [ubuntu/app-center#1750]
When I cancel the authentication process for updating/installing an app, I get an error message:

```
Error
We're sorry, but we're not sure what the error is.
```

![image](https://github.com/user-attachments/assets/445c9412-3067-4bec-957d-1d646e66badb)

But the log shows exactly what the issue is:

```
flutter: ERROR main: Error propagated to top-level
        SnapdException: SnapdException(kind: auth-cancelled, message: cancelled)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:479)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:916)
<asynchronous suspension>
#2      SnapModel.install (package:app_center/snapd/snap_model.dart:63)
<asynchronous suspension>
```

_Just a nitpick, because I got confused once due to this._
_¯\\_(ツ)_/¯, thanks <3_

**Comment by d-loose** [comment]
Thanks for the report! Overlooked that case in #1723

@anasereijo we've previously shown the raw error like this:

![image](https://github.com/user-attachments/assets/5230fbe5-8b05-40a6-a614-dd2bfb422b22)

I wonder if we should show an error at all if the user decides to cancel the polkit password prompt.
