### ISSUE TITLE
"Installed" button label not translatable

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/app-center#1758]
Ubuntu 24.04 with latest App Center that is fully translated in my (Czech) language. It looks like that the "Installed" button label is not marked for translation and is always in English (on non-English systems):

![screenshot](https://github.com/user-attachments/assets/0948478a-bd6e-4e25-8eb2-4590241545a5)

**Comment by spydon** [comment]
The `snapActionInstalledLabel` string is not translated in the Czech translation as far as I can see.

**Comment by AsciiWolf** [comment]
Ah, you are right! I was now able to find the string and it is indeed available for translation. The problem seems to be that the translated string was not yet synced from Weblate for some reason (see [this PR](https://github.com/ubuntu/app-center/pull/1722)).

**Comment by spydon** [comment]
@AsciiWolf it's now merged, so in the next release it'll be included. :)
