### ISSUE TITLE
Consistent Icons for all actions on Snap drop down menues

### ISSUE THREAD

**Issue by spydon** [ubuntu/app-center#1774]
Currently for example "Show details" is missing an icon and some icons are inconsistent across pages.

**Comment by spydon** [comment]
I forgot, did we decide which icons to use for these @anasereijo 
So we have these:
In list - 
![image](https://github.com/user-attachments/assets/fc0ac36f-6419-489a-aa5b-f9df4e49dfd2)

On page -
![image](https://github.com/user-attachments/assets/9dee8a99-b3bd-413e-a66c-6b94b440e298)

And fix so that they both have the bigger size, but that's #1775

**Comment by anasereijo** [comment]
The update icon in the dropdown should match the update icon used in the button.

I need to find an icon for 'open', but the more I look at it, the more I wonder if we need icons in the dropdown. :thinking_face: The logic is, if we have an icon here for 'Open' means that then the 'Open' button should always have the icon too. Feels a bit too much. Also, if we ever get more items here they will all need icons too! Let me think about this a bit better haha :)

**Comment by Feichtmeier** [comment]
> The update icon in the dropdown should match the update icon used in the button.
> 
> I need to find an icon for 'open', but the more I look at it, the more I wonder if we need icons in the dropdown. :thinking_face: The logic is, if we have an icon here for 'Open' means that then the 'Open' button should always have the icon too. Feels a bit too much. Also, if we ever get more items here they will all need icons too! Let me think about this a bit better haha :)

Maybe this one?
![grafik](https://github.com/user-attachments/assets/d5a4c646-f959-4647-ac18-601b4b21c4b9)

**Comment by spydon** [comment]
@Feichtmeier the icons were removed from the list instead, but maybe this icon could be used to indicate that the categories are now clickable, if it wouldn't look to cluttery...
