### ISSUE TITLE
App Center Not opening

### ISSUE THREAD

**Issue by MrSIHAB** [ubuntu/app-center#1780]
Today I deleted some snap packages. But After that I can't open the graphical app center. but i can access snap packages from command line. I reinstalled it. But App center is not opening yet. It doesn't give anything back at click response.
I don't know how to resolve it.

**Comment by Mr-Techtron** [comment]
@MrSIHAB I am facing the same issue after I deleted some snap packages. Can you please tell me how did you resolve this?
