### ISSUE TITLE
New gradients for categories in the expore page

### ISSUE THREAD

**Issue by spydon** [ubuntu/app-center#1802]
Cn we have the following gradient as a background? I had a look at the page and the colours of banners and changed a few. These gradients should exist somewhere, I believe. 

<img width="818" alt="Screenshot 2024-08-28 at 15 50 51" src="https://github.com/user-attachments/assets/90c7c47b-32eb-487a-a8c4-8ede9f2580d9">

_Originally posted by @anasereijo in https://github.com/ubuntu/app-center/issues/1801#issuecomment-2315587937_

**Comment by spydon** [comment]
@anasereijo where can I find the color specifications for the gradients?

**Comment by anasereijo** [comment]
@d-loose am I dreaming or you created a few gradients based on the ones I had on figma? do you remember that?

**Comment by d-loose** [comment]
I can't find them in Figma, but I added them in [this PR](https://github.com/ubuntu/app-center/pull/1331) from [here](https://github.com/ubuntu/app-center/discussions/1014#discussioncomment-4997933)

**Comment by spydon** [comment]
> I can't find them in Figma, but I added them in [this PR](https://github.com/ubuntu/app-center/pull/1331) from [here](https://github.com/ubuntu/app-center/discussions/1014#discussioncomment-4997933)

Here they are: https://www.figma.com/file/c4noYODoMPFNn04gsJVJLE?node-id=1%3A4664&type=design&fuid=1306624600528513668#515977686
(Ana pinged them to me over there)
