### ISSUE TITLE
Search results are sensitive to spaces

### ISSUE THREAD

**Issue by local-optimum** [ubuntu/app-center#1805]
![image](https://github.com/user-attachments/assets/6ce5ab4e-5829-4161-a192-b80ac6ad5d05)

Searching for 'libre office' does not return LibreOffice is a good example, searching for 'jupyter lab' doesn't return JupyterLab, I wonder if we can improve the search algorithm to be better at dealing with spaces.

**Comment by d-loose** [comment]
This is something that needs to be addressed on the store side. The search results displayed in the app center are consistent with the `snap` CLI and snapcraft.io

```
$ snap find "libre office"
Name            Version   Publisher                  Notes  Summary
mumble          v1.5.517  snapcrafters✪              -      Open Source, Low Latency, High Quality Voice Chat
atimerecording  1.4.19    gerold-gp-softwaretechnik  -      Free online time tracking for work, self-employed, sports and leisure.
```

![image](https://github.com/user-attachments/assets/2b285d39-d60c-4779-ada7-24dde0383a38)
