### ISSUE TITLE
Taiwanese Chinese(zh_TW) localization not working

### ISSUE THREAD

**Issue by brlin-tw** [ubuntu/app-center#1857]
I have the zh_TW locale set in the system settings:

```txt
$ locale
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_CN:en
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC=zh_TW.UTF-8
LC_TIME=zh_TW.UTF-8
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY=zh_TW.UTF-8
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER=zh_TW.UTF-8
LC_NAME=zh_TW.UTF-8
LC_ADDRESS=zh_TW.UTF-8
LC_TELEPHONE=zh_TW.UTF-8
LC_MEASUREMENT=zh_TW.UTF-8
LC_IDENTIFICATION=zh_TW.UTF-8
LC_ALL=
```

but the UI still shows zh_CN translated strings:

![Screenshot](https://github.com/user-attachments/assets/60f66ee1-9888-4bea-b7b2-074d52c47a7d)

Version: revision b2772108  (which should have zh_TW translation available since revision eea52798)

**Comment by d-loose** [comment]
Thanks for your report!
Currently there are no translations in [`app_zh_TW.arb`](https://github.com/ubuntu/app-center/blob/b2772108947c5a473166fbdceb01b6354235ed59/packages/app_center/lib/src/l10n/app_zh_TW.arb), so I think `app_zh.arb` is used as a fallback.
There might be something wrong with the weblate setup - the available components there are `zh_Hans` and `zh_Hant`. I'll have a closer look at this next week!

**Comment by brlin-tw** [comment]
@d-loose 

Thanks for your attention!  IMHO the `zh_Hans` and `zh_Hant` shouldn't be used and should be replaced with region-specific `zh_XX` locale codes.

**Comment by taijuin** [comment]
Maybe just the same way as other projects.
![123](https://github.com/user-attachments/assets/da4e360f-7d2e-4504-8f0f-ce5e74c05931)

**Comment by d-loose** [comment]
> @d-loose
> 
> Thanks for your attention! IMHO the `zh_Hans` and `zh_Hant` shouldn't be used and should be replaced with region-specific `zh_XX` locale codes.

Thanks, I've commented on our current setup in #1864. I think this is in line with the setup used on launchpad (see [here](https://translations.launchpad.net/ubuntu/plucky/+lang/zh_CN) and [here](https://translations.launchpad.net/ubuntu/plucky/+lang/zh_TW).
In principle Flutter supports a more [advanced locale setup](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#advanced-locale-definition), but I don't think this is supported by weblate (and we currently don't have the time to look into that, unfortunately).

A new build should land in the `latest/edge` and `2/edge` channels of the `snap-store` snap in a few hours. Please feel free to re-open this issue in case there are still some problems :)

**Comment by taijuin** [comment]
![001](https://github.com/user-attachments/assets/59a9bd27-061c-412a-9f3c-90eb8e77d6ff)

ok~!

Thanks

**Comment by brlin-tw** [comment]
@d-loose 

> A new build should land in the latest/edge and 2/edge channels of the snap-store snap in a few hours. Please feel free to re-open this issue in case there are still some problems :)

Apologies for the ignorance, I can verify the build in the 2/edge channel works, thanks for the help!
