### ISSUE TITLE
For softwares/packages from LP PPA, no changelog available

### ISSUE THREAD

**Issue by hsbasu** [ubuntu/app-center#290]
For softwares/packages installed from LP PPA, no changelog is available. Many of the users like me might be interested in the changelogs before updating a package. In contrast, Software Updater is showing changelogs.  (Screenshots attached)
![no_changelog](https://user-images.githubusercontent.com/41947504/192478444-c9894e59-3c07-425f-a44e-ca8a1259584f.png)
![with_changelog](https://user-images.githubusercontent.com/41947504/192478465-61629e0d-e7bf-4c7e-a626-ff1bc7c9dd4b.png)

**Comment by Feichtmeier** [comment]
CC @robert-ancell is this possible with packagekit.dart ?

**Comment by robert-ancell** [comment]
Packagekit provides some information via `PackageKitTransaction.getUpdateDetail` in the `PackageKitUpdateDetailEvent.changelog` event. I don't know if it contains all the information that is used in `Software` Updater", which gets these via a different method.

If we don't have all the information we need we either need to update the apt PackageKit backend to provide this, or get the changelogs directly (which we can do if we only need to support apt).

**Comment by Feichtmeier** [comment]
> Packagekit provides some information via `PackageKitTransaction.getUpdateDetail` in the `PackageKitUpdateDetailEvent.changelog` event. I don't know if it contains all the information that is used in `Software` Updater", which gets these via a different method.
> 
> If we don't have all the information we need we either need to update the apt PackageKit backend to provide this, or get the changelogs directly (which we can do if we only need to support apt).

Normal updates work fine with PackageKitTransaction.getUpdateDetail. Just not those from PPAs (prominent example might be google-chrome though I am not sure if those guys put any information into the PPA changelog at all)

**Comment by hsbasu** [comment]
@d-loose This app is supposed to be replacing the traditional *Software Updater*, right? But this feature is not yet available in this app.

**Comment by d-loose** [comment]
No, for the time being the new app center (together with the [new firmware updater](https://github.com/canonical/firmware-updater)) is only supposed to replace gnome-software.
