### ISSUE TITLE
Safe window size with gsettings after logout/login

### ISSUE THREAD

**Issue by fthx** [ubuntu/app-center#372]
Hi,

Not lost during a session, though.
Using snap, at least.

**Comment by fthx** [comment]
I noticed this because of responsive design.
By default, I get:

![image](https://user-images.githubusercontent.com/23138504/194766186-5a4d8ad8-e06e-4a82-899b-db1d330308bc.png)

and that does shorten menu labels if too long.

**Comment by Feichtmeier** [comment]
@Jupi007 reworked the navigation inside yaruwidgets
We've taken the dots because those translations can be extremely long and span into a second or third row
Which also looks weird
We plan to add tooltips to help with reading the string
Or should we reconsider to use TextOverflow.visible? @Jupi007

**Comment by fthx** [comment]
Oh from my pov, if the window get its position stored, there is no issue with dots. I think any user will resize the window in a way that fits his taste.

**Comment by Jupi007** [comment]
Oh, this is annoying...
I didn't though about a small word followed by a long one (which is quite common in French).

The only solution I found would be:

```dart
var label = 'Mes applications';
// ...
label.replaceAll(' ', '\u00A0');
```

![Capture d’écran du 2022-10-10 10-48-24](https://user-images.githubusercontent.com/36476595/194833821-1ba44562-cdfe-4be5-b8dc-3f2f0b5d97b6.png)

Which replace all spaces with an unbreakable character.
In fact we cannot expand the text widget as we are in a column, so we need to use a trick...

We could add a patch here, but this is not the good solution.
We need to fix that in yaru_widgets directly.

**Comment by fthx** [comment]
If you wrote "My Applications" that runs into the same issue in EN.
:-p

**Comment by Jupi007** [comment]
Indeed, but the english label is `My apps` ;)
In fact when I reworked the rail, all labels was all in one long word, so it hasn't this problem of text wrap with space.

**Comment by madsrh** [comment]
> Indeed, but the english label is My apps

This should be _Installed_

**Comment by Feichtmeier** [comment]
> > Indeed, but the english label is My apps
> 
> This should be _Installed_

I don't think so
We did not decide or discuss yet what should be included.

**Comment by madsrh** [comment]
> I don't think so

👍  Right!

What I meant to say was that these might change, so there's no reason to be nitpicking words (yet)
