### ISSUE TITLE
No option for conflicting packages

### ISSUE THREAD

**Issue by hsbasu** [ubuntu/app-center#405]
This has probably not been reported yet, because I could not found any related issue on GitHub and did not check the launchpad. Recently I built the yaru themes from master branch on my [launchpad PPA](https://launchpad.net/~mamolinux/+archive/ubuntu/daily-builds). This version breaks GNOME < 43 which is not available on my jammy(GNOME=42). When I used this app to update the installed packages it installed the yaru-theme-gnome-shell from my PPA and removed the gnome-desktop(ubuntu-desktop-minimal).

In contrast, the software updater(I think uses the same packagekit backend as ubuntu software.) unchecked the conflicting package while showing the updates, in this case yaru-theme-gnome-shell. I suggest there should be an option whether to remove the conflicting package or hold the update.

**Comment by Feichtmeier** [comment]
I don't know if this is actually supported by packagekit.dart (CC @robert-ancell )
This is really an edge case, but I agree that it is a case

**Comment by robert-ancell** [comment]
Looking at gnome-software it doesn't seem to be doing anything special with PackageKit that this project is not. I couldn't find anything in PackageKit that would be able to help with this.

You might be able to detect a problem like this by doing a simulated install, i.e.
```dart
await installTransaction.installPackages([packageId], transactionFlags: { PackageKitTransactionFlag.simulate });
```
You could work out what an install was about to do. However, the system could change after between the simulate and the actual install so it might not be completely reliable. I don't know if command line apt has the same issue of doe this in a more transactional way.

Please check if the problem occurs in gnome-software. If it does, then this is likely a limitation we're stuck with for the current time which would either be resolved by enhancing PackageKit or using apt directly in some way.
