### ISSUE TITLE
Use material badge instead of pub package

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/app-center#519]
Flutter recently added support for badges in the framework on the master channel https://github.com/flutter/flutter/pull/115002. 

This change collides with the Badges package which is currently used at the moment. The 3rd party package should probably be replaced by the framework version once it makes itself into the new stable.

![Screenshot from 2022-11-14 20-13-39](https://user-images.githubusercontent.com/73116038/201757527-ad5f32f7-f114-4284-9470-5e114f5bde7b.png)

**Comment by Feichtmeier** [comment]
Does the new flutter widget look the same or similar? I mean it's just a disk with a number and a little animation

**Comment by jpnurmi** [comment]
![image](https://user-images.githubusercontent.com/140617/201867798-6b4efe6f-cffa-4a7b-88df-79963a966c7f.png)

https://github.com/flutter/flutter/pull/114560

**Comment by whiskeyPeak** [comment]
Awesome! Just thought I'd give you guys a heads up.

**Comment by HansMuller** [comment]
Sorry about the collision. Until you decide to cut over to the Material library Badge, you can hide it:
```dart
import 'package:flutter/material.dart' hide Badge;
```

**Comment by Feichtmeier** [comment]
Mitigated by jp in #876 

But we could tinker to use the material badges instead since it is always nice to reduce deps
