### ISSUE TITLE
Improve linting and code analysing

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/app-center#568]
I think it would be nice to improve linting and code analysing by importing rules from `yaru_widgets`.
Some ones could be very interesting like `use_super_parameters`.

CC @Feichtmeier @jpnurmi

**Comment by jpnurmi** [comment]
`use_super_parameters` is nice! It hasn't been around for that long but it already feels old-fashioned when you see code not using super parameters... :nerd_face:
