### ISSUE TITLE
Improve "Connections"

### ISSUE THREAD

**Issue by madsrh** [ubuntu/app-center#616]
Just some thoughts on the connections widget

I think we should:
- [X] Rename _Connections_ to _Permissions_
2. Human readable labels - CUPS should be _Print documents_ and so on. This work has already been done for Software Center.
3. Group switches. The number of switches is overwhelming. No reason for audio-playback and audio-recording to be split and so on. This grouping has already been done for Software Center.
4. Add icons: easier at a glance rather than a huge wall of text.
5. Maybe use the widget only for info and hide the actual settings/switches in a popover ⚙️ 

Widget mockup / popover mockup / current widget:

![Ikke-navngivet](https://user-images.githubusercontent.com/3986894/205521206-8fb186bb-a061-490c-935b-7a9e700d0403.gif)

**Comment by Feichtmeier** [comment]
Snap connections work a bit different than on say android
There are a bunch of them that get auto connected if this is approved by those guys on snapcraft
The application can not really ask for them. So it needs to be obvious that you may need to switch them on. Thus I wouldn't hide them in a dialog.
The icons are a addition and the localisation is indeed needed. I still forgot to change the name in English xD it's long correct in German

**Comment by Feichtmeier** [comment]
No, they are for **_all_** users (sadly) because some apps do not even work if you do not toggle the connections on.

**Comment by Feichtmeier** [comment]
We can also try to group them, or improve thelook of the sections but we really should not hide them. Ubuntu != Android and Windows
Optimal would be a popup after you open the app for the first time, but this is stuff for snapcraft guys I think as we can not control this from the app

**Comment by madsrh** [comment]
> No, they are for all users (sadly) because some apps do not even work if you do not toggle the connections on.

Wow, I didn't know that! 

>  I do not agree with the rest : / 

No problem 👌

**Comment by anasereijo** [comment]
> Nice proposal @madsrh, I quite like the use of the icons 👍 and thanks for clarifying @Feichtmeier!
> 
> @madsrh maybe we can try grouping them as you suggested? I was told [these](https://snapcraft.io/docs/supported-interfaces) are the interfaces that we can display (correct me if I am wrong @Feichtmeier). As you can see, they all have descriptions, so perhaps we can include those as well. What do you guys think?

What would be the best way to group it? I can make a spreadsheet with all the [connections](https://snapcraft.io/docs/supported-interfaces), and we can try grouping them in there first? Whatever works best for all you :)

**Comment by anasereijo** [comment]
Update: I will have a catch-up with a member of the snap store team about how can we improve this, and how/if we can group items. I will post the outcome here.

**Comment by Feichtmeier** [comment]
Hello again on this issue :wave:

**Comment by madsrh** [comment]
@anasereijo has done some research last week, so hopefully she has some great ideas 💡

@Feichtmeier could we present the user with a dialog after the snap had finished installing?

It's a poor user experience atm, because as you mentioned, the app isn't working if you just launch it after installing. For Audacity (which I tried yesterday) I wasn't able to record audio, by checking the "audio-record" switch in connections/permissions. You would think by isn't name, it would be enough. But you ofc have to enable ALSA also. The everyday user wouldn't know this.

**Comment by Feichtmeier** [comment]
> @Feichtmeier could we present the user with a dialog after the snap had finished installing?

Yes, sure we could present it after installing and afterwards one could access it through... a button? 
Fast.-finger users might have a problem when they install and move on to install more. So we should prbly only show it if the user stays on the page while installing?

**Comment by madsrh** [comment]
> Fast.-finger users might have a problem when they install and move on to install more. So we should prbly only show it if the user stays on the page while installing?

Good point 🤔 What about a notification then? "Audacity has finished installing, click here to configure permissions"

**Comment by Feichtmeier** [comment]
Could be cool or spamy/hard to manage, depending on how many snaps you install at one :D 
We could maybe test it to see but I guess after 3 or 4 you will be confused

**Comment by Jupi007** [comment]
One thing that would be nice, is have a place that list all currently installing apps and those who finished their installation. So, the user can find them quickly to configure permissions and/or open the app directly from here.
Maybe in the "installed" apps page, and additionaly add a badge with the number of installing/new installed apps?

**Comment by madsrh** [comment]
Okay, there's multiple issues to tackle here, but here's a quick mockup of what I meant yesterday by the [installation-finished-dialog](https://github.com/ubuntu-flutter-community/software/issues/616#issuecomment-1382747631). Maybe it should even have an _allow all_ option 🤷‍♂️ 

![permissions](https://user-images.githubusercontent.com/3986894/212537521-07566cba-8f51-4282-b04a-a613b4308f0e.jpg)

**Comment by Jupi007** [comment]
It would be also nice to have a label on obscure stuff like `ALSA`, the end user just don't know what it means, and how it can be important.

**Comment by Feichtmeier** [comment]
> Okay, there's multiple issues to tackle here, but here's a quick mockup of what I meant yesterday by the [installation-finished-dialog](https://github.com/ubuntu-flutter-community/software/issues/616#issuecomment-1382747631). Maybe it should even have an _allow all_ option 🤷‍♂️ 
> 
> ![permissions](https://user-images.githubusercontent.com/3986894/212537521-07566cba-8f51-4282-b04a-a613b4308f0e.jpg)
> 

That looks 👍🙂 let's try this

**Comment by Feichtmeier** [comment]
@madsrh can we split this into multiple chunks? Then I would first "just move" this to the dialog in #777 and then implement your designs after ?

**Comment by madsrh** [comment]
> can we split this into multiple chunks? 

ofc! What every is easiest for you 😄  There's still the issue of the "fast fingers" you mentioned. I'll try to work on Pauls idea.

> It would be also nice to have a label on obscure stuff like ALSA, the end user just don't know what it means, and how it can be important.

+1 👍 

The [interface page](https://snapcraft.io/docs/supported-interfaces) has a short description and also a dedicated page for each, we could link to.

![image](https://user-images.githubusercontent.com/3986894/212549263-713dc84e-5652-4cab-a6a9-437dd34eff27.png)

**Comment by Feichtmeier** [comment]
okay and is this location of the "permissions" button good?
![grafik](https://user-images.githubusercontent.com/15329494/212549978-f6e6f685-e6d1-4434-ab74-37d240e910d2.png)
I feel like this is a bit too long

**Comment by Jupi007** [comment]
I really like the idea of a tooltip on an ℹ️ icon 👍

**Comment by Jupi007** [comment]
> okay and is this location of the "permissions" button good?
>
> I feel like this is a bit too long

Maybe move the version switcher on the upper row?

**Comment by madsrh** [comment]
> Maybe move the version switcher on the upper row?

I had the same thought, but I recall @anasereijo wanting only the snap/deb toggle on this row.

> okay and is this location of the "permissions" button good?

I don't have a better idea 🤔

**Comment by anasereijo** [comment]
This is not forgotten! Adding it to my to-do list (or shall I call it "to-read-think-and-reply list" 😁?)

**Comment by Feichtmeier** [comment]
> will the permissions change from version to version 

Yes this is possible as far as I know.

But I need to forward this to @kenvandine 

@kenvandine when a users switches the channel and then refreshes from that channel, can the list of wanted plugs/slots/connections change for this app?

**Comment by Feichtmeier** [comment]
> Hey all, sorry for the waiting.
> 
> I just had a catch-up with someone from the snap store team, and he will be helping us out on making the permissions more usable and more intuitive!
> 
> As a first step, we agreed that he will be looking at how we can categorise the interfaces. Hopefully I can share with you a first list of groupings, so we can all discuss, by next week.
> 
> That said, I suggest that we can agree with a solution for now, even the existing one, and iterate on this a bit more later on once we have a better idea on how/what we can change? What do you all think?
> 
> @Feichtmeier I agree that a button with a pop-up could work better than a section as we currently have. I have one question: will the permissions change from version to version? I don't mind it being next to the snap package, but I think I have to see it.

@anasereijo 

![grafik](https://user-images.githubusercontent.com/15329494/213142239-218e4904-8b67-484b-b417-caa2716d5179.png)
![grafik](https://user-images.githubusercontent.com/15329494/213142335-97e011c7-36ba-4e6e-afb5-befa4b67716e.png)
![grafik](https://user-images.githubusercontent.com/15329494/213142428-8ee26007-3ed6-4b70-8f50-7c6689322a05.png)

**Comment by anasereijo** [comment]
Not too bad, right? What do you all think?

**Comment by Feichtmeier** [comment]
It would help to get this merged if no-one disagrees to move the connections out of the settings and I could move on :) But ofc, if there is a veto I have no problems to focus on other stuff

**Comment by madsrh** [comment]
> It would help to get this merged...

+1  Go for it 😸

**Comment by Jupi007** [comment]
Yes +1 for this 🚀

**Comment by Feichtmeier** [comment]
ok it's now merged, I think this is a part success as this is now much more in the face
![grafik](https://user-images.githubusercontent.com/15329494/213156322-d96bcd2c-ce91-4a27-a770-0fe532603b2d.png)

Looking forward for the re-rededisgn of the switch-army

**Comment by anasereijo** [comment]
> Looking forward for the re-rededisgn of the switch-army

switch-army 😂😂😂

**Comment by anasereijo** [comment]
update: a draft for the categories/groups was done by someone from snap team. It will be reviewed by the team next week (hopefully). I will share the results here, so we can then work on a mock-up/solution. :)

**Comment by anasereijo** [comment]
waiting to hear back from the store team
