### ISSUE TITLE
AppFormat filter: change to be a three state dropdown

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#686]
### How it looks like:

![explorepage-packagefilter](https://user-images.githubusercontent.com/36884067/210573267-b3955614-95c6-450f-bec9-389b4efdd653.png)

![searchresults-packagefilter](https://user-images.githubusercontent.com/36884067/210573340-5501d64b-fe8a-4448-94cc-4a2b9e5ec8cb.png)

Currently, we display Snap packages by default. Ideally, we should show both packages (Snaps and Debs).
Also, when clicking on the dropdown, we have checkboxes to select between the 2 types of packages or to select both - this takes a few clicks. I propose having a dropdown with 3 options (see mockup below)
- All package types (selected by default)
- Snap packages
- Debian packages

### Proposal (this is just a wireframe, design is needed)

![23 04 v2 - Search results - packages dropdown](https://user-images.githubusercontent.com/36884067/210573623-5749878f-18ab-4959-a57e-3697ff39dd8b.jpg)

**Comment by whiskeyPeak** [comment]
Very small nit, but would it be possible to make the popup the same width as the button itself? As it is currently, there's a tiny amount overextending to the right. :D

**Comment by Feichtmeier** [comment]
Just for the protocoll

> Currently, we display Snap packages by default. Ideally, we should show both packages (Snaps and Debs).

This is fixed, thanks to dennis, you need to wait 2 secs at start and then the list of available app formats is filled up to be snap and deb

In general we should really move away from the mix of search and start page, as described here
https://github.com/ubuntu-flutter-community/software/discussions/698

I hope I find time to either create mock-ups or a rough-implementation to show you what I mean. IMO those filters on this page are wrong. This belongs only to the search page

**Comment by anasereijo** [comment]
> This is fixed, thanks to dennis, you need to wait 2 secs at start and then the list of available app formats is filled up to be snap and deb

I just checked and it is fixed, thanks 👍 
However, we still have the 2 checkboxes instead of display the 3 options as per my proposal:
<img width="222" alt="Screenshot 2023-01-11 at 15 35 51" src="https://user-images.githubusercontent.com/36884067/211848572-8d8e8e17-2dc8-47ce-aa90-f4de64364585.png">

> IMO those filters on this page are wrong. This belongs only to the search page
Agree. Let's remove them from explore page

**Comment by madsrh** [comment]
What about this one @whiskeyPeak ? I have no idea how complicated the code is. Is this low hanging fruit for you? I'm sure @Feichtmeier wouldn't mind 😃
