### ISSUE TITLE
Improve spacing for AppPage headers

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#731]
Yes, please push

There's a lot of spacing, so perhaps we should make it a bit tighter? But then again, this is an unusual huge window 😅 
![image](https://user-images.githubusercontent.com/3986894/211149976-a478b5c0-421c-4b23-8d7a-c3ef54687c6d.png)

_Originally posted by @madsrh in https://github.com/ubuntu-flutter-community/software/issues/561#issuecomment-1374460533_

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/211530135-2a90487b-6c7f-4d5c-8e2d-f651bfdce327.png)
![grafik](https://user-images.githubusercontent.com/15329494/211530183-101e2314-4e33-4fa1-8b16-980532977a40.png)
![grafik](https://user-images.githubusercontent.com/15329494/211530204-7fd2bf71-c790-4c9f-88ed-9753e8da118c.png)

**Comment by anasereijo** [comment]
Will try to mockup something tomorrow

**Comment by anasereijo** [comment]
I came up with a proposal for each size. Keep in mind that this is not pixel perfect, I did this quickly with a lot of screenshots cropped, like a collage 😅 If you need guidance on specific spacing or sizing, happy to provide more detail.

# size 1

### how it currently looks like
![size1](https://user-images.githubusercontent.com/36884067/213016200-f8a7a045-6460-47fa-87dd-6c4e99293d6b.png)

### proposal 
- moved all the content up a bit, so it has less white space at the top, making the app banner shorter;
- moved the version dropdown next to snap/debian button
- less space between snap/deb button and install button (to make it look grouped)
- install button below (the open, update buttons will be in the same row)
- basically what I've tried to do was grouping things a bit more. Icon and name/publisher are one group, all buttons another group and finally description. 

![size1-proposal](https://user-images.githubusercontent.com/36884067/213016298-37636ea6-7959-4a76-a741-a2eacb911d11.jpg)

# size 2

### how it currently looks like
![size2](https://user-images.githubusercontent.com/36884067/213017736-ad23e017-f24a-4dbf-a9e8-bad9f4fb9f65.png)

### proposal 
- the only change was to move the version dropdown next to snap/deb button
![size2-proposal](https://user-images.githubusercontent.com/36884067/213017828-e3a40192-aa94-4b5b-9c95-ac37164f13a2.jpg)


# size 3

### how it currently looks like
![size3](https://user-images.githubusercontent.com/36884067/213018172-d1510478-148c-423e-872c-2aed63a5c756.png)

### proposal 
- made the icon here slightly bigger. I felt that such a wide container deserved a bigger logo.
- moved the version dropdown next to snap/deb button
![size3-proposal](https://user-images.githubusercontent.com/36884067/213018269-d3cdfbd7-810c-4994-8f33-09800a055c08.jpg)

# size 4

### how it currently looks like
![size4](https://user-images.githubusercontent.com/36884067/213018557-ec713a0d-e821-4b7c-bd19-279bcc21cd85.png)

### proposal 
this is a weird one. I can only see it if I make the app a tiny bit bigger. Can we remove this version and keep it like the previous one? (size 3)

# size 5

### how it currently looks like
![size5](https://user-images.githubusercontent.com/36884067/213018860-4a8d0a75-0826-4325-be48-ab9aaf1cb156.png)

### proposal 
I also think this one is odd. The content on the right is too narrow, hard to read and see. What about keeping it the same layout as size 3 until the content on the right is the at least 3/4 of the size of the app header on the right?

# size 6

### how it currently looks like
![size6](https://user-images.githubusercontent.com/36884067/213019731-9f1fb7d9-c663-4d75-bbfc-68488d42cff9.png)

### proposal 
- basically same layout as size 1 but with a couple of tweaks:
  - icon size slightly bigger (same size as on size 3)
  - more space between groups (icon/image, buttons and description)

![size6-proposal](https://user-images.githubusercontent.com/36884067/213019768-4865e19b-c129-4a4d-be4d-7b7a639b722a.png)

I know this is a lot to take in, so please let me know if there are any questions. Also happy to jump on a quick call to go through this.

Thoughts are welcome!

**Comment by Feichtmeier** [comment]
That's 👍🙂

I'll try to focus on the individual sections first. When we're done with them I'll implement these design changes here
