### ISSUE TITLE
App-page Dependencies pop-up visual improvements 

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#739]
How it looks like:
<img width="552" alt="Screenshot 2023-01-11 at 12 08 28" src="https://user-images.githubusercontent.com/36884067/211802679-ae660bb2-40a3-45e1-9a59-9143a8bf7be7.png">

I was looking around Ubuntu OS, looking for dialogue pop-ups (not sure what you call them) with expand/collapse info, and found these 2 examples:

<img width="597" alt="Screenshot 2023-01-11 at 11 26 21" src="https://user-images.githubusercontent.com/36884067/211794662-91c5b48d-d9f3-4f6e-945a-545e548105bc.png">

<img width="481" alt="Screenshot 2023-01-11 at 11 35 50" src="https://user-images.githubusercontent.com/36884067/211796469-3a7fccbc-1c27-4c00-ad92-e7ae2c22f95a.png">

<img width="701" alt="Screenshot 2023-01-11 at 11 26 59" src="https://user-images.githubusercontent.com/36884067/211794794-470cbdf2-61fa-41f9-a9d1-9d3274e9f692.png">

I know it's a different design framework, but I think it would be nice to keep some consistency, at least on functionality. 
For instance, we could position the chevron before the text? Also, the text can be black and not as bold as per the examples.  Maybe also add a border when it expands.

I can mockup something if needed.

**Comment by madsrh** [comment]
I'm not sure I understand @anasereijo but all the examples you've found, are going to be incorporated into Software eventually 🤞 (long term plan), so IMO we don't need to worry about consistency and matching this old design.

> ...we could position the chevron before the text...

The current position comes from [Material design](https://m1.material.io/components/expansion-panels.html)
Do you mean like this? 

<img width="506px" src="https://user-images.githubusercontent.com/3986894/211800126-d96d80dc-c80e-4753-bd6d-5796f81c8b0c.png">

**Comment by anasereijo** [comment]
I meant in the popup. Unless we create a container (make it within a section with a border as per your examples) having the chevron on the right makes it look very floaty and not part of the link.

**Comment by madsrh** [comment]
> having the chevron on the right makes it look very floaty and not part of the link.

I agree and I understand now 😸 
Can you create a mockup for this issue?

**Comment by Jupi007** [comment]
Honestly, I really like the left aligned chevron idea :+1: 
This just need a few adaptation of the widget in yaru_widgets.

**Comment by Feichtmeier** [comment]
yes we just need a section option for expandables. Sometimes it's good to have it on the right, sometimes it's good to have it on the left

**Comment by Feichtmeier** [comment]
@anasereijo you don't need for *all* expandables, do you? 
Because I really like the arrows to be on the right for the expandable section in the app page

**Comment by anasereijo** [comment]
> @anasereijo you don't mean for _all_ expandables, do you? Because I really like the arrows to be on the right for the expandable section in the app page

I don't mean all expandable, no. As the tile of the issue says, I mean the Dependencies pop-up.

**Comment by Feichtmeier** [comment]
good, agree, the mouse travel is too long here. It looks like Paul finds time to fix this in our "widgets repository" (yaru widgets)

**Comment by anasereijo** [comment]
Here is (quick) mockup

![Frame 49](https://user-images.githubusercontent.com/36884067/211860008-5927d679-61e7-4de8-873f-410470b4a2cd.jpg)


![Frame 47](https://user-images.githubusercontent.com/36884067/211860002-e6025a60-07a6-46e0-bdf3-bd88c3c4f685.jpg)

**Comment by madsrh** [comment]
A quick mockup.  The width/padding of the BorderContainer should ofc align with the text 😉

![image](https://user-images.githubusercontent.com/3986894/213870586-fcff4e08-de6c-4ed7-ad8b-bf5da36c2a00.png)

**Comment by anasereijo** [comment]
> A quick mockup. The width/padding of the BorderContainer should ofc align with the text 😉
> 
> ![image](https://user-images.githubusercontent.com/3986894/213870586-fcff4e08-de6c-4ed7-ad8b-bf5da36c2a00.png)


Looks nice!! 

> A quick mockup. The width/padding of the BorderContainer should ofc align with the text 😉

I suppose the padding between the container and cancel/install buttons will also be reduced, right?

**Comment by madsrh** [comment]
> Looks nice!!

I think so too. I will be installing debian packages all day when this gets implemented 😜 

> I suppose the padding between the container and cancel/install buttons will also be reduced, right?

Ups, a bit too fast there. Yes, there's ofc a standard padding.

@Feichtmeier since "https://github.com/ubuntu/yaru_widgets.dart/issues/493" is merged, can we remove the  _External-issue_ tag?

**Comment by Feichtmeier** [comment]
SHould also be useable since I recently updated yaru widgets dep here
