### ISSUE TITLE
App-page - make rating an anchor link

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#740]
I would be nice if, when clicking on reviews at the top, make it scroll down to the reviews and ratings section. It's quite a common pattern across different stores.

<img width="817" alt="Screenshot 2023-01-11 at 11 39 58" src="https://user-images.githubusercontent.com/36884067/211797676-648365a9-b817-4a01-b6c0-a107a44436cc.png">

**Comment by whiskeyPeak** [comment]
@Feichtmeier I can give this one a go. There isn't much else I can get my hands dirty with :D

**Comment by Feichtmeier** [comment]
@whiskeyPeak sure you can try and see if you succeed without making the app page any less performant than it is. There is ScrollController.animateTo you could try but this might depend how big the screen is

**Comment by anasereijo** [comment]
Would this be a quick thing to do? If so, it would be nice to get it done – we noticed during user interviews some users trying to click on it.
