### ISSUE TITLE
Clicking on the menu entry to navigate back makes the yaruwindowtitlebar disappear

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/app-center#835]
![grafik](https://user-images.githubusercontent.com/15329494/213782441-94bed904-adaf-4f5d-837c-7a55954a65fb.png)

Poof! :magic_wand: It just disappears. No error :laughing:

**Comment by jpnurmi** [comment]
What menu entry?

**Comment by Feichtmeier** [comment]
Hehe 😊
There is the navigation feature that let's users click on the page item in the navigation bar **again** after they opened a specific app.

**Comment by Feichtmeier** [comment]
Note: didn't update yaruwidgets since yesterday so this might already been fixed

**Comment by Feichtmeier** [comment]
Note: i feel like we have a weird mix of hierarchies in this app which is the result of a lot of UI refactoring and moving things around.
Maybe we could improve this and only have one scaffold and let the outer navigation only replace the inner pages and have the search field change it's callback dependant on the currently selected page. Eventually this was too much to code around to satisfy this navigation request (valid, since it looks like more people do this than I expected)

**Comment by d-loose** [comment]
For me, only the window controls disappear:

https://user-images.githubusercontent.com/113362648/214001881-d2807b74-d46f-4431-a9f1-d01340b5c53c.mp4

**Comment by d-loose** [comment]
Resolved in the current app-center.
