### ISSUE TITLE
Add option to delete and search existing repositories

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#841]
Add option to delete and search existing repositories 

![image](https://user-images.githubusercontent.com/2129497/213844824-67600619-0ed6-4d8d-903b-725373a08ed4.png)

**Comment by Feichtmeier** [comment]
Hi @alculete 
Thanks for the idea. This should indeed be possible here. Sadly it is not possible with packagekit.dart. But we've created apt.dart which maybe help here

**Comment by d-loose** [comment]
We're currently not planning to include repository management.
