### ISSUE TITLE
Search with special characters gives bad query

### ISSUE THREAD

**Issue by madsrh** [ubuntu/app-center#863]
Poor title (again, sorry). Do we need an error message like the 🐣 ❓  or just allow special characters?
You can search with a **+** and **&** on _snapcraft.io_ although the results are the same as when you search without.

![image](https://user-images.githubusercontent.com/3986894/214166279-5329e455-c882-4409-af2e-31b468e6e210.png)

**Comment by Feichtmeier** [comment]
yep this comes from the back end, we could only prettify the output
Or eventually filter not allowed chars client side

**Comment by d-loose** [comment]
Seems like an issue in snapd:

```
$ nc -C -U /var/run/snapd.socket << eof
GET /v2/find?q=foo%2Bbar HTTP/1.0

eof
HTTP/1.0 400 Bad Request
Content-Type: application/json
Date: Fri, 27 Jan 2023 16:30:50 GMT
Content-Length: 109

{"type":"error","status-code":400,"status":"Bad Request","result":{"message":"bad query","kind":"bad-query"}}
```

**Comment by Feichtmeier** [comment]
Aha!!! I knew it xD
Thanks for investigating

**Comment by d-loose** [comment]
Snapd does this on purpose though:

```golang
// these characters might have special meaning on the search
// server, and don't form part of a reasonable search, so
// abort if they're included.
//
// "-" might also be special on the server, but it's also a
// valid part of a package name, so we let it pass
if strings.ContainsAny(searchTerm, `+=&|><!(){}[]^"~*?:\/`) {
	return nil, ErrBadQuery
}
```

https://github.com/snapcore/snapd/blob/2a78b3437d2a60cf6d9c5d247144b020e223d871/store/store.go#L1028

so maybe we are responsible for submitting sensible search queries after all.
