### ISSUE TITLE
Scrolling issue on package page

### ISSUE THREAD

**Issue by d-loose** [ubuntu/app-center#909]
Appears when there is a lot of content (found while debugging appstream metadata).

https://user-images.githubusercontent.com/113362648/215452577-8d3d3fa8-f898-42a8-a79f-fcd869651f58.mp4

**Comment by Feichtmeier** [comment]
Maybe this is due to the isExpanded props of the expandables

**Comment by d-loose** [comment]
Doesn't apply to the current design of the app page in app-center.
