### ISSUE TITLE
collections page (updates) add pop up to confirm removal of an app

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#988]
when clicking "delete" the user should get pop-up to confirm whether they want to delete the application or not

![](https://user-images.githubusercontent.com/15329494/217284268-7f0d80f9-7121-4977-a31c-fefa3862e099.png)

**Comment by Feichtmeier** [comment]
Yes if it works for debs too

**Comment by anasereijo** [comment]
> Yes if it works for debs too

just tested with Debs and I didn't get a notification

**Comment by madsrh** [comment]
> Yes if it works for debs too

I could have sworn that title said _"collections page (updates) add pop up to confirm removal of a snap"_ 😄  

Removing a deb: We should show this dependency dialog from the collection/manage page here as well. If there's no dependencies, we can just show a dialog similar to the remove snap. No have no idea how to do this #notlowhangingfruit

No offence, but dialog need a total makeover - it's totally confusing atm. Should I create a separate issue for this?

![image](https://user-images.githubusercontent.com/3986894/227032758-00b95aad-f43a-4863-a686-e4a87d9605aa.png)

**Comment by anasereijo** [comment]
> No offence, but dialog needs a makeover - it's a bit confusing IMHO. Should I create a separate issue for this?

sure! go for it

**Comment by Feichtmeier** [comment]
((( lol a Printer app? named Hannah is also kinda confusing xD )))
